package com.indore.pathome.spaces.service;

import com.indore.pathome.spaces.dto.GroundExecutiveCoverageCommand;
import com.indore.pathome.spaces.dto.GroundExecutiveCoverageEntry;
import com.indore.pathome.spaces.entity.EmployeeProfile;
import com.indore.pathome.spaces.entity.GroundExecutiveCoverage;
import com.indore.pathome.spaces.entity.Locality;
import com.indore.pathome.spaces.entity.Role;
import com.indore.pathome.spaces.entity.User;
import com.indore.pathome.spaces.exception.VisitOperationsConflictException;
import com.indore.pathome.spaces.repository.EmployeeProfileRepository;
import com.indore.pathome.spaces.repository.GroundExecutiveCoverageRepository;
import com.indore.pathome.spaces.repository.LocalityRepository;
import com.indore.pathome.spaces.repository.UserRepository;
import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.List;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@Import({GroundExecutiveSchedulingService.class, VisitOperationsAuthorizationService.class})
@EnabledIfEnvironmentVariable(named = "PATHOME_VISIT_OPERATIONS_POSTGRES_TEST", matches = "true")
class GroundExecutiveCoveragePostgresIntegrationTest {
    private static final String BASE_URL = System.getenv().getOrDefault(
            "SPRING_DATASOURCE_URL", "jdbc:postgresql://localhost:5432/pathome_db");
    private static final String USERNAME = System.getenv().getOrDefault("SPRING_DATASOURCE_USERNAME", "pathome");
    private static final String PASSWORD = System.getenv().getOrDefault("SPRING_DATASOURCE_PASSWORD", "");
    private static final String SCHEMA = "ge_coverage_test_" + UUID.randomUUID().toString().replace("-", "");

    @DynamicPropertySource
    static void database(DynamicPropertyRegistry registry) throws Exception {
        try (var connection = DriverManager.getConnection(BASE_URL, USERNAME, PASSWORD);
             Statement statement = connection.createStatement()) {
            statement.execute("CREATE SCHEMA " + SCHEMA);
            statement.execute("CREATE EXTENSION IF NOT EXISTS btree_gist WITH SCHEMA public");
            statement.execute("SET search_path TO " + SCHEMA);
            statement.execute("CREATE TABLE users ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email VARCHAR(255) UNIQUE, "
                    + "password_hash VARCHAR(255), full_name VARCHAR(255), phone_number VARCHAR(255), "
                    + "mobile_number_normalized VARCHAR(16), mobile_verified_at TIMESTAMP WITH TIME ZONE, "
                    + "role VARCHAR(255) NOT NULL, google_sub VARCHAR(255), free_visits_remaining INTEGER NOT NULL DEFAULT 5, "
                    + "landlord_activated_at TIMESTAMP, landlord_activated_by_user_id BIGINT, "
                    + "created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)");
            statement.execute("CREATE TABLE employee_profiles ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "user_id BIGINT NOT NULL UNIQUE REFERENCES users(id), role_type VARCHAR(255) NOT NULL, "
                    + "assigned_sector VARCHAR(255), base_salary NUMERIC(38, 2) NOT NULL, "
                    + "closed_deals_count INTEGER NOT NULL DEFAULT 0)");
            statement.execute("CREATE TABLE localities ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, city VARCHAR(255) NOT NULL, "
                    + "sector_name VARCHAR(255) NOT NULL, aliases VARCHAR(255), demand_score INTEGER, "
                    + "avg_rent_amount DOUBLE PRECISION, created_at TIMESTAMP, UNIQUE(city, sector_name))");
            statement.execute("CREATE TABLE property_visit_requests ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, status VARCHAR(40) NOT NULL)");
            statement.execute("CREATE TABLE visit_session_items ("
                    + "session_id BIGINT NOT NULL, listing_id BIGINT NOT NULL, "
                    + "confirmation_status VARCHAR(24) NOT NULL DEFAULT 'PENDING', "
                    + "availability_confirmed_at TIMESTAMP WITH TIME ZONE, "
                    + "confirmed_by_user_id BIGINT REFERENCES users(id), removed_at TIMESTAMP WITH TIME ZONE)");
        }

        Flyway.configure().dataSource(BASE_URL, USERNAME, PASSWORD)
                .schemas(SCHEMA).defaultSchema(SCHEMA)
                .baselineOnMigrate(true).baselineVersion("36").target("37")
                .locations("classpath:db/migration").load().migrate();

        String schemaUrl = BASE_URL + (BASE_URL.contains("?") ? "&" : "?") + "currentSchema=" + SCHEMA;
        registry.add("spring.datasource.url", () -> schemaUrl);
        registry.add("spring.datasource.username", () -> USERNAME);
        registry.add("spring.datasource.password", () -> PASSWORD);
        registry.add("spring.flyway.enabled", () -> "false");
        registry.add("spring.jpa.hibernate.ddl-auto", () -> "none");
    }

    @AfterAll
    static void dropSchema() throws Exception {
        try (var connection = DriverManager.getConnection(BASE_URL, USERNAME, PASSWORD);
             Statement statement = connection.createStatement()) {
            statement.execute("DROP SCHEMA IF EXISTS " + SCHEMA + " CASCADE");
        }
    }

    @Autowired private GroundExecutiveSchedulingService scheduling;
    @Autowired private GroundExecutiveCoverageRepository coverage;
    @Autowired private EmployeeProfileRepository employees;
    @Autowired private LocalityRepository localities;
    @Autowired private UserRepository users;
    @Autowired private JdbcTemplate jdbc;

    @Test
    @Transactional(propagation = Propagation.NOT_SUPPORTED)
    void replacingCoverageRetainingExistingLocalityCommitsOnceAndRejectsInvalidInput() {
        User admin = user("admin", Role.ROLE_ADMIN);
        User ground = user("ground", Role.ROLE_GROUND_BOY);
        EmployeeProfile employee = employees.saveAndFlush(
                new EmployeeProfile(ground, "GROUND_BOY", null, BigDecimal.ZERO));
        Locality retained = localities.saveAndFlush(new Locality("Example City", "Central", null, null, null));
        Locality removed = localities.saveAndFlush(new Locality("Example City", "North", null, null, null));
        Locality added = localities.saveAndFlush(new Locality("Example City", "East", null, null, null));
        Locality otherCity = localities.saveAndFlush(new Locality("Other City", "West", null, null, null));

        var initial = scheduling.replaceCoverage(admin.getId(), ground.getId(), new GroundExecutiveCoverageCommand(0L,
                List.of(new GroundExecutiveCoverageEntry(null, retained.getId()),
                        new GroundExecutiveCoverageEntry(null, removed.getId()))));
        assertEquals(2, initial.coverage().size());

        assertThrows(IllegalArgumentException.class, () -> scheduling.replaceCoverage(admin.getId(), ground.getId(),
                new GroundExecutiveCoverageCommand(initial.version(), List.of(
                        new GroundExecutiveCoverageEntry(null, retained.getId()),
                        new GroundExecutiveCoverageEntry(null, retained.getId())))));
        assertThrows(IllegalArgumentException.class, () -> scheduling.replaceCoverage(admin.getId(), ground.getId(),
                new GroundExecutiveCoverageCommand(initial.version(), List.of(
                        new GroundExecutiveCoverageEntry("Example City", otherCity.getId())))));
        assertThrows(VisitOperationsConflictException.class, () -> scheduling.replaceCoverage(admin.getId(), ground.getId(),
                new GroundExecutiveCoverageCommand(initial.version() - 1, List.of(
                        new GroundExecutiveCoverageEntry(null, retained.getId())))));

        var replaced = scheduling.replaceCoverage(admin.getId(), ground.getId(), new GroundExecutiveCoverageCommand(
                initial.version(), List.of(new GroundExecutiveCoverageEntry(null, retained.getId()),
                        new GroundExecutiveCoverageEntry(null, added.getId()))));

        List<GroundExecutiveCoverage> persisted = coverage
                .findBySchedulingProfileEmployeeProfileIdOrderByCityAsc(employee.getId());
        assertEquals(2, persisted.size());
        assertEquals(1, persisted.stream().filter(entry -> retained.getId().equals(
                entry.getLocality() == null ? null : entry.getLocality().getId())).count());
        assertEquals(1, persisted.stream().filter(entry -> added.getId().equals(
                entry.getLocality() == null ? null : entry.getLocality().getId())).count());
        assertEquals(0, persisted.stream().filter(entry -> removed.getId().equals(
                entry.getLocality() == null ? null : entry.getLocality().getId())).count());
        assertEquals(2, jdbc.queryForObject("SELECT count(*) FROM ground_executive_coverage WHERE employee_profile_id = ?",
                Integer.class, employee.getId()));
        assertEquals(2, replaced.coverage().size());
    }

    private User user(String prefix, Role role) {
        User user = new User();
        user.setEmail(prefix + "-" + UUID.randomUUID() + "@example.test");
        user.setFullName(prefix);
        user.setRole(role);
        return users.saveAndFlush(user);
    }
}
