package com.indore.pathome.spaces.dto;

public enum RecommendationReason {
    TENANT_PREFERRED_TIME_MATCH,
    PROPERTY_WINDOW_MATCH,
    SCHEDULING_ACTIVE,
    SHIFT_MATCH,
    NO_UNAVAILABILITY_CONFLICT,
    RESERVATION_FEASIBLE,
    TRAVEL_FEASIBLE,
    LOCATION_USED_FOR_FIRST_LEG,
    LOCATION_UNAVAILABLE_FALLBACK_USED,
    LOCATION_DEGRADED_FALLBACK_USED,
    LOCALITY_COVERAGE_MATCH,
    CITY_COVERAGE_MATCH,
    LOWER_FUTURE_WORKLOAD,
    TRAVEL_ESTIMATE_UNCERTAIN
}
