package com.indore.pathome.spaces.dto;

public enum RecommendationRejectionReason {
    COVERAGE_MISMATCH,
    TENANT_WINDOW_MISMATCH,
    PROPERTY_WINDOW_MISMATCH,
    RESERVATION_OVERLAP,
    FIRST_LEG_TRAVEL_INFEASIBLE,
    NEXT_LEG_TRAVEL_INFEASIBLE,
    SHIFT_MISMATCH,
    UNAVAILABILITY_CONFLICT,
    NO_FEASIBLE_TIME
}
