package com.indore.pathome.spaces.dto;

public enum RecommendationStatus {
    RECOMMENDATION_AVAILABLE,
    NO_ELIGIBLE_GE,
    NO_FEASIBLE_TIME,
    INSUFFICIENT_TENANT_AVAILABILITY,
    PROPERTY_AVAILABILITY_INCOMPLETE,
    LOCATION_UNAVAILABLE_FALLBACK_USED,
    TRAVEL_ESTIMATE_UNCERTAIN,
    SESSION_NOT_SCHEDULABLE,
    RECOMMENDATION_STALE,
    CONFLICT
}
