-- LessorProfile truthfulness hardening.
-- Addresses four post-V26/V27 review findings without touching applied migrations.

-- FINDING 1: display_name must be nullable.
-- Profiles for incomplete users, FIELD_TEAM, CRM, IMPORT etc. legitimately have
-- no name yet. Do not fabricate a name; let display_name be NULL until a real
-- name is provided.
ALTER TABLE lessor_profiles
    ALTER COLUMN display_name DROP NOT NULL;

-- FINDING 2: Nullify the V26 fabricated "Lessor <id>" placeholder names.
-- Only clears values that were provably generated by the V26 backfill:
--   source_type = SELF_SERVICE
--   AND linked_user_id IS NOT NULL
--   AND display_name = 'Lessor ' || linked_user_id  (exact V26 template)
--   AND the source User has a NULL or blank full_name
-- Genuine names matching "Lessor <digits>" by coincidence are NOT cleared
-- because they cannot originate from user data (V26 only wrote the template
-- when full_name was null/blank, so if a real User.full_name existed we
-- would have used it instead).
UPDATE lessor_profiles lp
SET    display_name = NULL,
       updated_at   = CURRENT_TIMESTAMP
FROM   users u
WHERE  lp.linked_user_id     = u.id
  AND  lp.source_type        = 'SELF_SERVICE'
  AND  lp.display_name       = 'Lessor ' || lp.linked_user_id::text
  AND  (u.full_name IS NULL OR TRIM(u.full_name) = '');

-- FINDING 3: Restore genuine +91 9999999999 that V27 wrongly zeroed.
-- V27 unconditionally set mobile_number = NULL where it found '+91 9999999999'.
-- That value could legitimately be the User's actual phone number.
-- Restore it only where provenance proves it came from the User record:
--   SELF_SERVICE profile whose mobile_number is currently NULL
--   AND the linked User's phone_number is exactly '+91 9999999999'
-- The old V26 fabricated sentinel was written ONLY when the User had no phone,
-- so if User.phone_number itself contains this value it is source data.
UPDATE lessor_profiles lp
SET    mobile_number = u.phone_number,
       updated_at    = CURRENT_TIMESTAMP
FROM   users u
WHERE  lp.linked_user_id  = u.id
  AND  lp.source_type     = 'SELF_SERVICE'
  AND  lp.mobile_number   IS NULL
  AND  u.phone_number     = '+91 9999999999';
