CREATE TABLE supported_cities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL,
    display_name VARCHAR(160) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_supported_cities_code UNIQUE (code),
    CONSTRAINT ck_supported_cities_code CHECK (code ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    CONSTRAINT ck_supported_cities_display_name CHECK (btrim(display_name) <> ''),
    CONSTRAINT ck_supported_cities_version CHECK (version >= 0)
);

CREATE INDEX idx_supported_cities_active_display_name
    ON supported_cities (display_name)
    WHERE active = TRUE;

CREATE TABLE operating_teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id BIGINT NOT NULL,
    code VARCHAR(64) NOT NULL,
    display_name VARCHAR(160) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_operating_teams_city FOREIGN KEY (city_id) REFERENCES supported_cities (id),
    CONSTRAINT uk_operating_teams_city_code UNIQUE (city_id, code),
    CONSTRAINT ck_operating_teams_code CHECK (code ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    CONSTRAINT ck_operating_teams_display_name CHECK (btrim(display_name) <> ''),
    CONSTRAINT ck_operating_teams_version CHECK (version >= 0)
);

ALTER TABLE localities
    ADD COLUMN supported_city_id BIGINT,
    ADD CONSTRAINT fk_localities_supported_city
        FOREIGN KEY (supported_city_id) REFERENCES supported_cities (id);

CREATE INDEX idx_localities_supported_city_id
    ON localities (supported_city_id)
    WHERE supported_city_id IS NOT NULL;

INSERT INTO supported_cities (code, display_name, active)
VALUES
    ('indore', 'Indore', TRUE),
    ('bhopal', 'Bhopal', TRUE),
    ('pune', 'Pune', TRUE)
ON CONFLICT (code) DO NOTHING;

WITH unambiguous_locality_cities AS (
    SELECT l.id AS locality_id, MIN(c.id) AS supported_city_id
    FROM localities l
    JOIN supported_cities c
      ON lower(btrim(l.city)) = lower(btrim(c.display_name))
    GROUP BY l.id
    HAVING COUNT(*) = 1
)
UPDATE localities l
SET supported_city_id = mapped.supported_city_id
FROM unambiguous_locality_cities mapped
WHERE l.id = mapped.locality_id;
