ALTER TABLE employee_profiles
    ALTER COLUMN role_type DROP NOT NULL,
    ALTER COLUMN base_salary DROP NOT NULL,
    ALTER COLUMN base_salary DROP DEFAULT,
    ADD COLUMN staff_active BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN staff_activated_at TIMESTAMPTZ,
    ADD COLUMN staff_deactivated_at TIMESTAMPTZ,
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0,
    ADD CONSTRAINT ck_employee_profiles_staff_version CHECK (version >= 0);

CREATE TABLE staff_access_grants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    capability VARCHAR(40) NOT NULL,
    scope_type VARCHAR(16) NOT NULL,
    city_id BIGINT,
    team_id BIGINT,
    effective_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    granted_by_user_id BIGINT,
    revoked_by_user_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    grant_reason_code VARCHAR(64) NOT NULL,
    revoke_reason_code VARCHAR(64),
    provisioning_source VARCHAR(32) NOT NULL,
    CONSTRAINT fk_staff_grants_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_staff_grants_city FOREIGN KEY (city_id) REFERENCES supported_cities (id),
    CONSTRAINT fk_staff_grants_team FOREIGN KEY (team_id) REFERENCES operating_teams (id),
    CONSTRAINT fk_staff_grants_grantor FOREIGN KEY (granted_by_user_id) REFERENCES users (id),
    CONSTRAINT fk_staff_grants_revoker FOREIGN KEY (revoked_by_user_id) REFERENCES users (id),
    CONSTRAINT ck_staff_grants_capability CHECK (capability IN (
        'STAFF_ADMIN', 'CITY_TEAM_ADMIN', 'OPS_INTAKE', 'OPS_COORDINATE', 'OPS_SUPERVISE'
    )),
    CONSTRAINT ck_staff_grants_scope_type CHECK (scope_type IN ('GLOBAL', 'CITY', 'TEAM')),
    CONSTRAINT ck_staff_grants_scope_shape CHECK (
        (scope_type = 'GLOBAL' AND city_id IS NULL AND team_id IS NULL)
        OR (scope_type = 'CITY' AND city_id IS NOT NULL AND team_id IS NULL)
        OR (scope_type = 'TEAM' AND city_id IS NULL AND team_id IS NOT NULL)
    ),
    CONSTRAINT ck_staff_grants_capability_scope CHECK (
        (capability = 'STAFF_ADMIN' AND scope_type = 'GLOBAL')
        OR (capability = 'CITY_TEAM_ADMIN' AND scope_type = 'CITY')
        OR (capability = 'OPS_INTAKE' AND scope_type = 'CITY')
        OR (capability IN ('OPS_COORDINATE', 'OPS_SUPERVISE') AND scope_type = 'TEAM')
    ),
    CONSTRAINT ck_staff_grants_interval CHECK (expires_at IS NULL OR expires_at > effective_at),
    CONSTRAINT ck_staff_grants_admin_no_expiry CHECK (capability <> 'STAFF_ADMIN' OR expires_at IS NULL),
    CONSTRAINT ck_staff_grants_revocation_shape CHECK (
        (revoked_at IS NULL AND revoked_by_user_id IS NULL AND revoke_reason_code IS NULL)
        OR (revoked_at IS NOT NULL AND revoke_reason_code IS NOT NULL)
    ),
    CONSTRAINT ck_staff_grants_reason CHECK (grant_reason_code ~ '^[A-Z][A-Z0-9_]{0,63}$'),
    CONSTRAINT ck_staff_grants_revoke_reason CHECK (
        revoke_reason_code IS NULL OR revoke_reason_code ~ '^[A-Z][A-Z0-9_]{0,63}$'
    ),
    CONSTRAINT ck_staff_grants_provisioning_source CHECK (
        provisioning_source IN ('ADMIN_API', 'INITIAL_BOOTSTRAP', 'OPERATOR_RECOVERY')
    )
);

CREATE INDEX idx_staff_grants_user_cap_effective
    ON staff_access_grants (user_id, capability, effective_at, expires_at)
    WHERE revoked_at IS NULL;
CREATE INDEX idx_staff_grants_user_unrevoked
    ON staff_access_grants (user_id, effective_at)
    WHERE revoked_at IS NULL;
CREATE INDEX idx_staff_grants_city_cap_effective
    ON staff_access_grants (city_id, capability, effective_at)
    WHERE scope_type = 'CITY' AND revoked_at IS NULL;
CREATE INDEX idx_staff_grants_team_cap_effective
    ON staff_access_grants (team_id, capability, effective_at)
    WHERE scope_type = 'TEAM' AND revoked_at IS NULL;
CREATE UNIQUE INDEX uq_staff_grants_global_start
    ON staff_access_grants (user_id, capability, effective_at)
    WHERE scope_type = 'GLOBAL' AND revoked_at IS NULL;
CREATE UNIQUE INDEX uq_staff_grants_city_start
    ON staff_access_grants (user_id, capability, city_id, effective_at)
    WHERE scope_type = 'CITY' AND revoked_at IS NULL;
CREATE UNIQUE INDEX uq_staff_grants_team_start
    ON staff_access_grants (user_id, capability, team_id, effective_at)
    WHERE scope_type = 'TEAM' AND revoked_at IS NULL;
CREATE INDEX idx_staff_grants_global_admin_history
    ON staff_access_grants (effective_at)
    WHERE capability = 'STAFF_ADMIN' AND scope_type = 'GLOBAL';

CREATE FUNCTION protect_staff_access_grant_history() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Staff grant history cannot be deleted';
    END IF;
    IF (NEW.id, NEW.user_id, NEW.capability, NEW.scope_type, NEW.city_id, NEW.team_id,
        NEW.effective_at, NEW.expires_at, NEW.granted_by_user_id, NEW.created_at,
        NEW.grant_reason_code, NEW.provisioning_source)
       IS DISTINCT FROM
       (OLD.id, OLD.user_id, OLD.capability, OLD.scope_type, OLD.city_id, OLD.team_id,
        OLD.effective_at, OLD.expires_at, OLD.granted_by_user_id, OLD.created_at,
        OLD.grant_reason_code, OLD.provisioning_source) THEN
        RAISE EXCEPTION 'Staff grant facts are immutable';
    END IF;
    IF OLD.revoked_at IS NOT NULL
       AND (NEW.revoked_at, NEW.revoked_by_user_id, NEW.revoke_reason_code)
           IS DISTINCT FROM (OLD.revoked_at, OLD.revoked_by_user_id, OLD.revoke_reason_code) THEN
        RAISE EXCEPTION 'Staff grant revocation is final';
    END IF;
    IF OLD.revoked_at IS NULL AND NEW.revoked_at IS NULL
       AND (NEW.revoked_by_user_id IS NOT NULL OR NEW.revoke_reason_code IS NOT NULL) THEN
        RAISE EXCEPTION 'Staff grant revocation fields require a revocation timestamp';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_staff_access_grant_immutable_facts
    BEFORE UPDATE OR DELETE ON staff_access_grants
    FOR EACH ROW EXECUTE FUNCTION protect_staff_access_grant_history();

CREATE FUNCTION prevent_operational_audit_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'Operational audit events are immutable';
END;
$$ LANGUAGE plpgsql;

CREATE TABLE operational_audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actor_kind VARCHAR(32) NOT NULL,
    actor_user_id BIGINT,
    operator_reference VARCHAR(120),
    action_code VARCHAR(64) NOT NULL,
    target_type VARCHAR(48) NOT NULL,
    target_id BIGINT NOT NULL,
    city_id BIGINT,
    team_id BIGINT,
    operation_id VARCHAR(100),
    correlation_id VARCHAR(100),
    reason_code VARCHAR(64) NOT NULL,
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT fk_operational_audit_actor FOREIGN KEY (actor_user_id) REFERENCES users (id),
    CONSTRAINT fk_operational_audit_city FOREIGN KEY (city_id) REFERENCES supported_cities (id),
    CONSTRAINT fk_operational_audit_team FOREIGN KEY (team_id) REFERENCES operating_teams (id),
    CONSTRAINT ck_operational_audit_actor_kind CHECK (actor_kind IN ('USER', 'DEPLOYMENT_OPERATOR')),
    CONSTRAINT ck_operational_audit_actor_shape CHECK (
        (actor_kind = 'USER' AND actor_user_id IS NOT NULL AND operator_reference IS NULL)
        OR (actor_kind = 'DEPLOYMENT_OPERATOR' AND actor_user_id IS NULL
            AND operator_reference ~ '^[A-Z0-9][A-Z0-9:_-]{0,119}$')
    ),
    CONSTRAINT ck_operational_audit_action CHECK (action_code ~ '^[A-Z][A-Z0-9_]{0,63}$'),
    CONSTRAINT ck_operational_audit_target CHECK (target_type ~ '^[A-Z][A-Z0-9_]{0,47}$'),
    CONSTRAINT ck_operational_audit_reason CHECK (reason_code ~ '^[A-Z][A-Z0-9_]{0,63}$'),
    CONSTRAINT ck_operational_audit_details_object CHECK (jsonb_typeof(details) = 'object')
);

CREATE INDEX idx_operational_audit_occurred_at ON operational_audit_events (occurred_at DESC);
CREATE INDEX idx_operational_audit_target ON operational_audit_events (target_type, target_id, occurred_at DESC);
CREATE TRIGGER trg_operational_audit_immutable
    BEFORE UPDATE OR DELETE ON operational_audit_events
    FOR EACH ROW EXECUTE FUNCTION prevent_operational_audit_mutation();
