DO $$
DECLARE
    parent_table REGCLASS := to_regclass(format('%I.%I', current_schema(), 'parser_training_examples'));
    parent_id_type TEXT;
    parent_id_identity "char";
    parent_id_default TEXT;
    parent_id_sequence TEXT;
    parent_id_attnum SMALLINT;
    field_table REGCLASS;
    field_id_attnum SMALLINT;
    example_id_attnum SMALLINT;
    field_name_attnum SMALLINT;
    field_id_sequence REGCLASS;
    sequence_last_value BIGINT;
    sequence_called BOOLEAN;
    sequence_increment BIGINT;
    sequence_max_value BIGINT;
    sequence_cache_size BIGINT;
    sequence_cycles BOOLEAN;
    sequence_next_value NUMERIC;
    generator_identity "char";
    generator_default TEXT;
    maximum_existing_id BIGINT;
    constraint_name TEXT;
    constraint_type "char";
    constraint_columns SMALLINT[];
    equivalent_name TEXT;
    mismatch_columns TEXT;
    duplicate_found BOOLEAN;
    orphan_found BOOLEAN;
    index_name TEXT;
    index_columns TEXT[];
    actual_index_oid OID;
    actual_index_table OID;
    actual_index_unique BOOLEAN;
    actual_index_valid BOOLEAN;
    actual_index_btree BOOLEAN;
    actual_index_unpredicated BOOLEAN;
    actual_index_columns TEXT[];
    index_relation_name TEXT;
    rendered_columns TEXT;
BEGIN
    IF parent_table IS NULL THEN
        RAISE EXCEPTION 'Cannot create parser_field_reviews: parser_training_examples is missing';
    END IF;

    SELECT format_type(a.atttypid, a.atttypmod), a.attidentity,
           pg_get_expr(d.adbin, d.adrelid),
           a.attnum
      INTO parent_id_type, parent_id_identity, parent_id_default, parent_id_attnum
      FROM pg_attribute a
      LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
     WHERE a.attrelid = parent_table AND a.attname = 'id'
       AND a.attnum > 0 AND NOT a.attisdropped;

    IF parent_id_type = 'bigint' THEN
        IF EXISTS (SELECT 1 FROM parser_training_examples) THEN
            RAISE EXCEPTION 'Cannot align parser_training_examples.id with its mapped VARCHAR(36) type: legacy BIGINT rows exist';
        END IF;
        IF EXISTS (SELECT 1 FROM pg_constraint WHERE contype = 'f' AND confrelid = parent_table) THEN
            RAISE EXCEPTION 'Cannot align parser_training_examples.id while other foreign keys reference it';
        END IF;

        IF parent_id_identity <> '' THEN
            ALTER TABLE parser_training_examples ALTER COLUMN id DROP IDENTITY;
        ELSE
            parent_id_sequence := pg_get_serial_sequence('parser_training_examples', 'id');
            IF parent_id_default IS NOT NULL AND parent_id_sequence IS NULL THEN
                RAISE EXCEPTION 'Cannot align parser_training_examples.id with an unrecognized default';
            END IF;
            ALTER TABLE parser_training_examples ALTER COLUMN id DROP DEFAULT;
            IF parent_id_sequence IS NOT NULL THEN
                EXECUTE format('ALTER SEQUENCE %s OWNED BY NONE', parent_id_sequence::REGCLASS);
                EXECUTE format('DROP SEQUENCE %s', parent_id_sequence::REGCLASS);
            END IF;
        END IF;
        ALTER TABLE parser_training_examples
            ALTER COLUMN id TYPE VARCHAR(36) USING id::TEXT;
        parent_id_type := 'character varying(36)';
    ELSIF parent_id_type <> 'character varying(36)' THEN
        RAISE EXCEPTION 'Cannot create parser_field_reviews: parser_training_examples.id has incompatible type %', parent_id_type;
    END IF;

    SELECT a.attnum
      INTO parent_id_attnum
      FROM pg_attribute a
     WHERE a.attrelid = parent_table AND a.attname = 'id'
       AND a.attnum > 0 AND NOT a.attisdropped;

    IF parent_id_type IS NULL OR parent_id_attnum IS NULL THEN
        RAISE EXCEPTION 'Cannot create parser_field_reviews: parser_training_examples.id is missing';
    END IF;

    IF to_regclass(format('%I.%I', current_schema(), 'parser_field_reviews')) IS NULL THEN
        CREATE TABLE parser_field_reviews (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
            example_id VARCHAR(36) NOT NULL,
            field_name VARCHAR(64) NOT NULL,
            predicted_value TEXT,
            reviewed_value TEXT NOT NULL,
            source_text TEXT,
            source_start INTEGER,
            source_end INTEGER,
            was_corrected BOOLEAN NOT NULL,
            evidence_supported BOOLEAN NOT NULL,
            value_valid BOOLEAN NOT NULL,
            training_eligible BOOLEAN NOT NULL,
            exclusion_reason VARCHAR(500),
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
            CONSTRAINT parser_field_reviews_pkey PRIMARY KEY (id),
            CONSTRAINT fk_parser_field_review_example
                FOREIGN KEY (example_id) REFERENCES parser_training_examples(id),
            CONSTRAINT uk_parser_field_example_name UNIQUE (example_id, field_name)
        );
    END IF;

    field_table := to_regclass(format('%I.%I', current_schema(), 'parser_field_reviews'));
    IF (SELECT relkind FROM pg_class WHERE oid = field_table) <> 'r' THEN
        RAISE EXCEPTION 'Existing parser_field_reviews is not a regular PostgreSQL table';
    END IF;

    WITH expected(column_name, column_type, required) AS (
        VALUES
            ('id', 'bigint', TRUE),
            ('example_id', 'character varying(36)', TRUE),
            ('field_name', 'character varying(64)', TRUE),
            ('predicted_value', 'text', FALSE),
            ('reviewed_value', 'text', TRUE),
            ('source_text', 'text', FALSE),
            ('source_start', 'integer', FALSE),
            ('source_end', 'integer', FALSE),
            ('was_corrected', 'boolean', TRUE),
            ('evidence_supported', 'boolean', TRUE),
            ('value_valid', 'boolean', TRUE),
            ('training_eligible', 'boolean', TRUE),
            ('exclusion_reason', 'character varying(500)', FALSE),
            ('created_at', 'timestamp without time zone', TRUE)
    )
    SELECT string_agg(e.column_name, ', ' ORDER BY e.column_name)
      INTO mismatch_columns
      FROM expected e
      LEFT JOIN pg_attribute a ON a.attrelid = field_table
                              AND a.attname = e.column_name
                              AND a.attnum > 0
                              AND NOT a.attisdropped
     WHERE a.attname IS NULL
        OR CASE
               WHEN e.column_name = 'created_at' THEN a.atttypid <> 'timestamp without time zone'::REGTYPE
               ELSE format_type(a.atttypid, a.atttypmod) <> e.column_type
           END
        OR a.attnotnull <> e.required;

    IF mismatch_columns IS NOT NULL THEN
        RAISE EXCEPTION 'Existing parser_field_reviews has incompatible or missing columns: %', mismatch_columns;
    END IF;

    SELECT a.attnum INTO field_id_attnum
      FROM pg_attribute a WHERE a.attrelid = field_table AND a.attname = 'id'
       AND a.attnum > 0 AND NOT a.attisdropped;
    SELECT a.attnum INTO example_id_attnum
      FROM pg_attribute a WHERE a.attrelid = field_table AND a.attname = 'example_id'
       AND a.attnum > 0 AND NOT a.attisdropped;
    SELECT a.attnum INTO field_name_attnum
      FROM pg_attribute a WHERE a.attrelid = field_table AND a.attname = 'field_name'
       AND a.attnum > 0 AND NOT a.attisdropped;

    IF NOT EXISTS (
        SELECT 1 FROM pg_attribute a
         WHERE a.attrelid = field_table AND a.attname = 'id'
           AND a.attidentity IN ('a', 'd')
    ) AND pg_get_serial_sequence('parser_field_reviews', 'id') IS NULL THEN
        RAISE EXCEPTION 'Existing parser_field_reviews.id has no identity/sequence generator';
    END IF;

    SELECT conname, conkey INTO constraint_name, constraint_columns
      FROM pg_constraint WHERE conrelid = field_table AND contype = 'p';
    IF FOUND THEN
        IF constraint_columns <> ARRAY[field_id_attnum]::SMALLINT[] THEN
            RAISE EXCEPTION 'Existing parser_field_reviews primary key is incompatible';
        END IF;
        IF constraint_name <> 'parser_field_reviews_pkey' THEN
            IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = field_table
                       AND conname = 'parser_field_reviews_pkey') THEN
                RAISE EXCEPTION 'Constraint name parser_field_reviews_pkey is already used incompatibly';
            END IF;
            EXECUTE format('ALTER TABLE %I.%I RENAME CONSTRAINT %I TO %I',
                current_schema(), 'parser_field_reviews', constraint_name, 'parser_field_reviews_pkey');
        END IF;
    ELSE
        SELECT EXISTS (
            SELECT 1 FROM parser_field_reviews GROUP BY id HAVING count(*) > 1
        ) INTO duplicate_found;
        IF duplicate_found THEN
            RAISE EXCEPTION 'Existing parser_field_reviews contains duplicate IDs; primary key cannot be added safely';
        END IF;
        ALTER TABLE parser_field_reviews ADD CONSTRAINT parser_field_reviews_pkey PRIMARY KEY (id);
    END IF;

    SELECT conname INTO constraint_name
      FROM pg_constraint WHERE conrelid = field_table AND conname = 'uk_parser_field_example_name';
    IF FOUND THEN
        SELECT contype, conkey INTO constraint_type, constraint_columns
          FROM pg_constraint WHERE conrelid = field_table AND conname = 'uk_parser_field_example_name';
        IF constraint_type <> 'u' OR constraint_columns <> ARRAY[example_id_attnum, field_name_attnum]::SMALLINT[] THEN
            RAISE EXCEPTION 'Constraint uk_parser_field_example_name has an incompatible definition';
        END IF;
    ELSE
        SELECT conname INTO equivalent_name FROM pg_constraint
         WHERE conrelid = field_table AND contype = 'u'
           AND conkey = ARRAY[example_id_attnum, field_name_attnum]::SMALLINT[]
         ORDER BY conname LIMIT 1;
        IF equivalent_name IS NOT NULL THEN
            EXECUTE format('ALTER TABLE %I.%I RENAME CONSTRAINT %I TO %I',
                current_schema(), 'parser_field_reviews', equivalent_name, 'uk_parser_field_example_name');
        ELSE
            SELECT EXISTS (
                SELECT 1 FROM parser_field_reviews GROUP BY example_id, field_name HAVING count(*) > 1
            ) INTO duplicate_found;
            IF duplicate_found THEN
                RAISE EXCEPTION 'Existing parser_field_reviews has duplicate example/field pairs; unique constraint cannot be added safely';
            END IF;
            ALTER TABLE parser_field_reviews
                ADD CONSTRAINT uk_parser_field_example_name UNIQUE (example_id, field_name);
        END IF;
    END IF;

    SELECT conname INTO constraint_name FROM pg_constraint
     WHERE conrelid = field_table AND conname = 'fk_parser_field_review_example';
    IF FOUND THEN
        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint con
             WHERE con.conrelid = field_table AND con.conname = 'fk_parser_field_review_example'
               AND con.contype = 'f'
               AND con.conkey = ARRAY[example_id_attnum]::SMALLINT[]
               AND con.confrelid = parent_table
               AND con.confkey = ARRAY[parent_id_attnum]::SMALLINT[]
               AND con.confupdtype = 'a' AND con.confdeltype = 'a'
               AND con.convalidated AND NOT con.condeferrable
        ) THEN
            RAISE EXCEPTION 'Constraint fk_parser_field_review_example has an incompatible definition';
        END IF;
    ELSE
        SELECT conname INTO equivalent_name FROM pg_constraint
         WHERE conrelid = field_table AND contype = 'f'
           AND conkey = ARRAY[example_id_attnum]::SMALLINT[]
           AND confrelid = parent_table
           AND confkey = ARRAY[parent_id_attnum]::SMALLINT[]
           AND confupdtype = 'a' AND confdeltype = 'a'
           AND convalidated AND NOT condeferrable
         ORDER BY conname LIMIT 1;
        IF equivalent_name IS NOT NULL THEN
            EXECUTE format('ALTER TABLE %I.%I RENAME CONSTRAINT %I TO %I',
                current_schema(), 'parser_field_reviews', equivalent_name, 'fk_parser_field_review_example');
        ELSE
            SELECT EXISTS (
                SELECT 1 FROM parser_field_reviews r
                LEFT JOIN parser_training_examples e ON e.id = r.example_id
                WHERE e.id IS NULL
            ) INTO orphan_found;
            IF orphan_found THEN
                RAISE EXCEPTION 'Existing parser_field_reviews has rows without parser_training_examples; foreign key cannot be added safely';
            END IF;
            IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = field_table
                       AND contype = 'f' AND conkey = ARRAY[example_id_attnum]::SMALLINT[]) THEN
                RAISE EXCEPTION 'Existing parser_field_reviews.example_id has an incompatible foreign key';
            END IF;
            ALTER TABLE parser_field_reviews
                ADD CONSTRAINT fk_parser_field_review_example
                FOREIGN KEY (example_id) REFERENCES parser_training_examples(id);
        END IF;
    END IF;

    FOR index_name, index_columns IN
        SELECT * FROM (VALUES
            ('idx_parser_field_example_eligible', ARRAY['example_id', 'training_eligible']::TEXT[]),
            ('idx_parser_field_name_eligible', ARRAY['field_name', 'training_eligible']::TEXT[])
        ) AS expected(name, columns)
    LOOP
        actual_index_oid := NULL;
        actual_index_table := NULL;
        actual_index_unique := NULL;
        actual_index_valid := NULL;
        actual_index_btree := NULL;
        actual_index_unpredicated := NULL;
        actual_index_columns := NULL;
        index_relation_name := NULL;

        SELECT cls.oid, ix.indrelid, ix.indisunique, ix.indisvalid,
               access_method.amname = 'btree', ix.indpred IS NULL,
               ARRAY(SELECT pg_get_indexdef(ix.indexrelid, position, TRUE)
                       FROM generate_series(1, ix.indnkeyatts) AS position
                      ORDER BY position)
          INTO actual_index_oid, actual_index_table, actual_index_unique,
               actual_index_valid, actual_index_btree, actual_index_unpredicated,
               actual_index_columns
          FROM pg_class cls
          JOIN pg_namespace ns ON ns.oid = cls.relnamespace
          LEFT JOIN pg_index ix ON ix.indexrelid = cls.oid
          LEFT JOIN pg_am access_method ON access_method.oid = cls.relam
         WHERE ns.nspname = current_schema() AND cls.relname = index_name;

        IF actual_index_oid IS NOT NULL THEN
            IF actual_index_table <> field_table OR actual_index_unique
               OR NOT actual_index_valid OR NOT actual_index_btree
               OR NOT actual_index_unpredicated OR actual_index_columns <> index_columns THEN
                RAISE EXCEPTION 'Index % exists with an incompatible definition', index_name;
            END IF;
        ELSE
            SELECT cls.relname INTO index_relation_name
              FROM pg_class cls
              JOIN pg_namespace ns ON ns.oid = cls.relnamespace
              JOIN pg_index ix ON ix.indexrelid = cls.oid
              JOIN pg_am access_method ON access_method.oid = cls.relam
             WHERE ns.nspname = current_schema() AND ix.indrelid = field_table
               AND NOT ix.indisunique AND ix.indisvalid AND ix.indpred IS NULL
               AND access_method.amname = 'btree'
               AND ix.indnatts = ix.indnkeyatts
               AND ARRAY(SELECT pg_get_indexdef(ix.indexrelid, position, TRUE)
                           FROM generate_series(1, ix.indnkeyatts) AS position
                          ORDER BY position) = index_columns
             ORDER BY cls.relname LIMIT 1;

            IF index_relation_name IS NOT NULL THEN
                EXECUTE format('ALTER INDEX %I.%I RENAME TO %I',
                    current_schema(), index_relation_name, index_name);
            ELSE
                SELECT string_agg(format('%I', column_name), ', ' ORDER BY ordinality)
                  INTO rendered_columns
                  FROM unnest(index_columns) WITH ORDINALITY AS columns(column_name, ordinality);
                EXECUTE format('CREATE INDEX %I ON %s (%s)', index_name, field_table, rendered_columns);
            END IF;
        END IF;
    END LOOP;

    -- Explicit historical IDs may be ahead of their owned identity/serial sequence.
    -- Reject generators whose next value cannot be kept above the preserved IDs.
    EXECUTE format('SELECT COALESCE(MAX(id), 0) FROM %I.%I',
        current_schema(), 'parser_field_reviews') INTO maximum_existing_id;
    field_id_sequence := pg_get_serial_sequence(
        format('%I.%I', current_schema(), 'parser_field_reviews'), 'id')::REGCLASS;
    IF field_id_sequence IS NULL THEN
        RAISE EXCEPTION 'parser_field_reviews.id generator disappeared during schema reconciliation';
    END IF;
    SELECT a.attidentity, pg_get_expr(d.adbin, d.adrelid)
      INTO generator_identity, generator_default
      FROM pg_attribute a
      LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
     WHERE a.attrelid = field_table AND a.attname = 'id';
    IF generator_identity NOT IN ('a', 'd')
       AND generator_default IS DISTINCT FROM format('nextval(%L::regclass)', field_id_sequence::TEXT) THEN
        RAISE EXCEPTION 'parser_field_reviews.id has an incompatible sequence default';
    END IF;
    SELECT seqincrement, seqmax, seqcache, seqcycle
      INTO sequence_increment, sequence_max_value, sequence_cache_size, sequence_cycles
      FROM pg_sequence WHERE seqrelid = field_id_sequence;
    IF sequence_increment IS NULL OR sequence_increment <= 0
       OR sequence_cycles OR sequence_cache_size <> 1 THEN
        RAISE EXCEPTION 'parser_field_reviews.id requires a noncycling ascending generator with cache 1';
    END IF;
    EXECUTE format('SELECT last_value, is_called FROM %s', field_id_sequence)
        INTO sequence_last_value, sequence_called;
    sequence_next_value := sequence_last_value::NUMERIC
        + CASE WHEN sequence_called THEN sequence_increment ELSE 0 END;
    IF maximum_existing_id >= sequence_max_value THEN
        RAISE EXCEPTION 'parser_field_reviews.id generator cannot advance beyond preserved ID %', maximum_existing_id;
    END IF;
    IF sequence_next_value <= maximum_existing_id THEN
        IF maximum_existing_id::NUMERIC + sequence_increment > sequence_max_value THEN
            RAISE EXCEPTION 'parser_field_reviews.id generator cannot advance beyond preserved ID %', maximum_existing_id;
        END IF;
        PERFORM setval(field_id_sequence, maximum_existing_id, TRUE);
    ELSIF sequence_next_value > sequence_max_value THEN
        RAISE EXCEPTION 'parser_field_reviews.id generator is exhausted';
    END IF;
END
$$;
