package com.indore.pathome.spaces.service.searchlearning;

import java.util.List;

public record AliasPolicyDecision(Action action, AliasLifecycle nextState, List<Reason> reasons, double confidenceLowerBound) {
    public enum Action { PAUSED, BUILD_EVIDENCE, ENTER_SHADOW, KEEP_SHADOW, PROMOTE, KEEP_ACTIVE,
        DEGRADE, RECOVER, AUTO_DISABLE, RESET_FOR_RELEARNING, WAIT_COOLDOWN, BLOCKED_MANUAL_DISABLE }
    public enum Reason { DISABLED_BY_CONFIGURATION, MANUAL_DISABLE_LOCK, UNSUPPORTED_ENTITY,
        INVALID_CANONICAL_TARGET, DETERMINISTIC_CONFLICT, CONFLICTING_ACTIVE_ALIAS,
        INSUFFICIENT_EVIDENCE, INSUFFICIENT_UNIQUE_SESSIONS, CANDIDATE_TOO_NEW,
        INSUFFICIENT_TIME_DIVERSITY, COMPETING_TARGETS, LOW_CONFIDENCE_BOUND,
        SUSPICIOUS_SESSION_CONCENTRATION, BURST_CONCENTRATION, INSUFFICIENT_SHADOW_VOLUME,
        LOW_SHADOW_AGREEMENT, LOW_SHADOW_CONFIDENCE, HEALTHY_FOR_PROMOTION,
        RECENT_HEALTH_DEGRADED, RECENT_HEALTH_RECOVERED, RECENT_HEALTH_UNHEALTHY,
        INSUFFICIENT_RECENT_HEALTH, HEALTHY, COOLDOWN, FRESH_EVIDENCE_REQUIRED }
}
