package com.indore.pathome.spaces.entity;

import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.FlywayException;
import org.flywaydb.core.api.configuration.FluentConfiguration;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.datasource.init.ScriptUtils;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

/** Exercises V46 against the confirmed unmanaged-but-compatible parser review table shape. */
@EnabledIfEnvironmentVariable(named = "PATHOME_PACKAGE5_FLYWAY_TEST", matches = "true")
class ParserFieldReviewMigrationPostgresTest {
    @Test
    void v46PreservesCompatibleUnmanagedParserReviewRows() throws Exception {
        String url = System.getenv().getOrDefault("SPRING_DATASOURCE_URL", "jdbc:postgresql://localhost:5432/pathome_db");
        String username = System.getenv().getOrDefault("SPRING_DATASOURCE_USERNAME", "pathome");
        String password = System.getenv().getOrDefault("SPRING_DATASOURCE_PASSWORD", "");
        String schema = "pathome_parser_field_upgrade_" + UUID.randomUUID().toString().replace("-", "");
        String exampleId = UUID.randomUUID().toString();
        long reviewId;

        try (Connection connection = DriverManager.getConnection(url, username, password);
             Statement statement = connection.createStatement()) {
            statement.execute("CREATE SCHEMA " + schema);
            try {
                connection.setSchema(schema);
                ScriptUtils.executeSqlScript(connection,
                        new ClassPathResource("db/baseline/pathome-v1-legacy-core.sql"));
                var throughV45 = flyway(url, username, password, schema).target("45").load().migrate();
                assertTrue(throughV45.success);
                assertEquals("bigint", text(connection, "SELECT data_type FROM information_schema.columns "
                        + "WHERE table_schema=current_schema() AND table_name='parser_training_examples' AND column_name='id'"));

                // Reproduce the confirmed application-owned historical shape before V46 takes ownership.
                statement.execute("ALTER TABLE parser_training_examples ALTER COLUMN id DROP DEFAULT");
                statement.execute("ALTER SEQUENCE parser_training_examples_id_seq OWNED BY NONE");
                statement.execute("DROP SEQUENCE parser_training_examples_id_seq");
                statement.execute("ALTER TABLE parser_training_examples ALTER COLUMN id TYPE VARCHAR(36) USING id::TEXT");
                statement.execute("INSERT INTO parser_training_examples(id,created_by) VALUES ('" + exampleId
                        + "','migration-fixture')");
                statement.execute("CREATE TABLE parser_field_reviews ("
                        + "id BIGINT GENERATED BY DEFAULT AS IDENTITY,"
                        + "example_id VARCHAR(36) NOT NULL,"
                        + "field_name VARCHAR(64) NOT NULL,"
                        + "predicted_value TEXT,"
                        + "reviewed_value TEXT NOT NULL,"
                        + "source_text TEXT,"
                        + "source_start INTEGER,"
                        + "source_end INTEGER,"
                        + "was_corrected BOOLEAN NOT NULL,"
                        + "evidence_supported BOOLEAN NOT NULL,"
                        + "value_valid BOOLEAN NOT NULL,"
                        + "training_eligible BOOLEAN NOT NULL,"
                        + "exclusion_reason VARCHAR(500),"
                        + "created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,"
                        + "CONSTRAINT parser_field_reviews_pkey PRIMARY KEY (id),"
                        + "CONSTRAINT fk_parser_field_review_example FOREIGN KEY (example_id) REFERENCES parser_training_examples(id),"
                        + "CONSTRAINT uk_parser_field_example_name UNIQUE (example_id,field_name))");
                statement.execute("CREATE INDEX idx_parser_field_example_eligible ON parser_field_reviews(example_id,training_eligible)");
                statement.execute("CREATE INDEX idx_parser_field_name_eligible ON parser_field_reviews(field_name,training_eligible)");

                try (ResultSet row = statement.executeQuery("INSERT INTO parser_field_reviews"
                        + "(id,example_id,field_name,predicted_value,reviewed_value,source_text,source_start,source_end,"
                        + "was_corrected,evidence_supported,value_valid,training_eligible,exclusion_reason,created_at) "
                        + "VALUES (900001,'" + exampleId + "','rentAmount','1000','1200','rent 1200',5,9,TRUE,TRUE,TRUE,TRUE,NULL,CURRENT_TIMESTAMP) "
                        + "RETURNING id")) {
                    assertTrue(row.next());
                    reviewId = row.getLong(1);
                }

                Flyway v46 = flyway(url, username, password, schema).target("46").load();
                var result = v46.migrate();
                assertTrue(result.success);
                assertEquals(1, result.migrationsExecuted);
                assertEquals("46", result.targetSchemaVersion.toString());
                assertDoesNotThrow(v46::validate);

                assertEquals(1, count(connection, "SELECT count(*) FROM parser_field_reviews"));
                assertEquals(1, count(connection, "SELECT count(*) FROM parser_field_reviews WHERE id=" + reviewId
                        + " AND example_id='" + exampleId + "' AND field_name='rentAmount'"
                        + " AND predicted_value='1000' AND reviewed_value='1200' AND source_text='rent 1200'"
                        + " AND source_start=5 AND source_end=9 AND was_corrected AND evidence_supported"
                        + " AND value_valid AND training_eligible AND exclusion_reason IS NULL"));
                assertEquals(46, count(connection, "SELECT max(version::integer) FROM flyway_schema_history "
                        + "WHERE type='SQL' AND success"));
                assertEquals(2, count(connection, "SELECT count(*) FROM pg_indexes WHERE schemaname=current_schema() "
                        + "AND indexname IN ('idx_parser_field_example_eligible','idx_parser_field_name_eligible')"));
                long nextReviewId;
                try (ResultSet row = statement.executeQuery("INSERT INTO parser_field_reviews"
                        + "(example_id,field_name,reviewed_value,was_corrected,evidence_supported,value_valid,"
                        + "training_eligible,created_at) VALUES ('" + exampleId
                        + "','securityDeposit','1200',FALSE,TRUE,TRUE,FALSE,CURRENT_TIMESTAMP) RETURNING id")) {
                    assertTrue(row.next());
                    nextReviewId = row.getLong(1);
                }
                assertTrue(nextReviewId > reviewId,
                        "V46 must advance a lagging identity generator beyond preserved historical IDs");
            } finally {
                statement.execute("DROP SCHEMA IF EXISTS " + schema + " CASCADE");
            }
        }
    }

    @Test
    void v46KeepsNormalAscendingHistoricalGeneratorAheadOfRows() throws Exception {
        verifyHistoricalGenerator(false);
    }

    @Test
    void v46RejectsDescendingHistoricalGeneratorWithoutLosingRows() throws Exception {
        verifyHistoricalGenerator(true);
    }

    private static void verifyHistoricalGenerator(boolean descending) throws Exception {
        String url = System.getenv().getOrDefault("SPRING_DATASOURCE_URL", "jdbc:postgresql://localhost:5432/pathome_db");
        String username = System.getenv().getOrDefault("SPRING_DATASOURCE_USERNAME", "pathome");
        String password = System.getenv().getOrDefault("SPRING_DATASOURCE_PASSWORD", "");
        String schema = "pathome_parser_field_generator_" + UUID.randomUUID().toString().replace("-", "");
        String exampleId = UUID.randomUUID().toString();

        try (Connection connection = DriverManager.getConnection(url, username, password);
             Statement statement = connection.createStatement()) {
            statement.execute("CREATE SCHEMA " + schema);
            try {
                connection.setSchema(schema);
                ScriptUtils.executeSqlScript(connection,
                        new ClassPathResource("db/baseline/pathome-v1-legacy-core.sql"));
                assertTrue(flyway(url, username, password, schema).target("45").load().migrate().success);
                statement.execute("ALTER TABLE parser_training_examples ALTER COLUMN id DROP DEFAULT");
                statement.execute("ALTER SEQUENCE parser_training_examples_id_seq OWNED BY NONE");
                statement.execute("DROP SEQUENCE parser_training_examples_id_seq");
                statement.execute("ALTER TABLE parser_training_examples ALTER COLUMN id TYPE VARCHAR(36) USING id::TEXT");
                statement.execute("INSERT INTO parser_training_examples(id,created_by) VALUES ('" + exampleId
                        + "','migration-fixture')");
                statement.execute("CREATE TABLE parser_field_reviews ("
                        + "id BIGINT GENERATED BY DEFAULT AS IDENTITY "
                        + (descending ? "(INCREMENT BY -1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1)" : "")
                        + ",example_id VARCHAR(36) NOT NULL,field_name VARCHAR(64) NOT NULL,predicted_value TEXT,"
                        + "reviewed_value TEXT NOT NULL,source_text TEXT,source_start INTEGER,source_end INTEGER,"
                        + "was_corrected BOOLEAN NOT NULL,evidence_supported BOOLEAN NOT NULL,value_valid BOOLEAN NOT NULL,"
                        + "training_eligible BOOLEAN NOT NULL,exclusion_reason VARCHAR(500),"
                        + "created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,"
                        + "CONSTRAINT parser_field_reviews_pkey PRIMARY KEY (id),"
                        + "CONSTRAINT fk_parser_field_review_example FOREIGN KEY (example_id) REFERENCES parser_training_examples(id),"
                        + "CONSTRAINT uk_parser_field_example_name UNIQUE (example_id,field_name))");
                long historicalId;
                String insert = descending
                        ? "INSERT INTO parser_field_reviews(id,example_id,field_name,reviewed_value,"
                            + "was_corrected,evidence_supported,value_valid,training_eligible,created_at) VALUES (900001,'"
                            + exampleId + "','rentAmount','1200',FALSE,TRUE,TRUE,FALSE,CURRENT_TIMESTAMP) RETURNING id"
                        : "INSERT INTO parser_field_reviews(example_id,field_name,reviewed_value,"
                            + "was_corrected,evidence_supported,value_valid,training_eligible,created_at) VALUES ('"
                            + exampleId + "','rentAmount','1200',FALSE,TRUE,TRUE,FALSE,CURRENT_TIMESTAMP) RETURNING id";
                try (ResultSet row = statement.executeQuery(insert)) {
                    assertTrue(row.next());
                    historicalId = row.getLong(1);
                }

                Flyway v46 = flyway(url, username, password, schema).target("46").load();
                if (descending) {
                    FlywayException failure = assertThrows(FlywayException.class, v46::migrate);
                    Throwable cause = failure;
                    while (cause.getCause() != null) cause = cause.getCause();
                    assertTrue(cause.getMessage().contains("noncycling ascending generator"),
                            "V46 must clearly reject the descending generator");
                } else {
                    assertTrue(v46.migrate().success);
                    try (ResultSet row = statement.executeQuery("INSERT INTO parser_field_reviews"
                            + "(example_id,field_name,reviewed_value,was_corrected,evidence_supported,value_valid,"
                            + "training_eligible,created_at) VALUES ('" + exampleId
                            + "','securityDeposit','1200',FALSE,TRUE,TRUE,FALSE,CURRENT_TIMESTAMP) RETURNING id")) {
                        assertTrue(row.next());
                        assertTrue(row.getLong(1) > historicalId,
                                "an already-ahead ascending identity must keep generating above preserved IDs");
                    }
                }
                assertEquals(1, count(connection, "SELECT count(*) FROM parser_field_reviews WHERE id="
                        + historicalId + " AND example_id='" + exampleId + "' AND field_name='rentAmount'"
                        + " AND reviewed_value='1200'"));
            } finally {
                statement.execute("DROP SCHEMA IF EXISTS " + schema + " CASCADE");
            }
        }
    }

    @Test
    void v46RejectsNotValidHistoricalReviewForeignKeyWithoutLosingRows() throws Exception {
        String url = System.getenv().getOrDefault("SPRING_DATASOURCE_URL", "jdbc:postgresql://localhost:5432/pathome_db");
        String username = System.getenv().getOrDefault("SPRING_DATASOURCE_USERNAME", "pathome");
        String password = System.getenv().getOrDefault("SPRING_DATASOURCE_PASSWORD", "");
        String schema = "pathome_parser_field_not_valid_" + UUID.randomUUID().toString().replace("-", "");
        String exampleId = UUID.randomUUID().toString();

        try (Connection connection = DriverManager.getConnection(url, username, password);
             Statement statement = connection.createStatement()) {
            statement.execute("CREATE SCHEMA " + schema);
            try {
                connection.setSchema(schema);
                ScriptUtils.executeSqlScript(connection,
                        new ClassPathResource("db/baseline/pathome-v1-legacy-core.sql"));
                assertTrue(flyway(url, username, password, schema).target("45").load().migrate().success);
                statement.execute("ALTER TABLE parser_training_examples ALTER COLUMN id DROP DEFAULT");
                statement.execute("ALTER SEQUENCE parser_training_examples_id_seq OWNED BY NONE");
                statement.execute("DROP SEQUENCE parser_training_examples_id_seq");
                statement.execute("ALTER TABLE parser_training_examples ALTER COLUMN id TYPE VARCHAR(36) USING id::TEXT");
                statement.execute("INSERT INTO parser_training_examples(id,created_by) VALUES ('" + exampleId
                        + "','migration-fixture')");
                statement.execute("CREATE TABLE parser_field_reviews ("
                        + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "example_id VARCHAR(36) NOT NULL,field_name VARCHAR(64) NOT NULL,predicted_value TEXT,"
                        + "reviewed_value TEXT NOT NULL,source_text TEXT,source_start INTEGER,source_end INTEGER,"
                        + "was_corrected BOOLEAN NOT NULL,evidence_supported BOOLEAN NOT NULL,value_valid BOOLEAN NOT NULL,"
                        + "training_eligible BOOLEAN NOT NULL,exclusion_reason VARCHAR(500),"
                        + "created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,"
                        + "CONSTRAINT uk_parser_field_example_name UNIQUE (example_id,field_name))");
                statement.execute("CREATE INDEX idx_parser_field_example_eligible ON parser_field_reviews(example_id,training_eligible)");
                statement.execute("CREATE INDEX idx_parser_field_name_eligible ON parser_field_reviews(field_name,training_eligible)");
                statement.execute("INSERT INTO parser_field_reviews(id,example_id,field_name,reviewed_value,"
                        + "was_corrected,evidence_supported,value_valid,training_eligible,created_at) VALUES (77,'"
                        + exampleId + "','rentAmount','1200',FALSE,TRUE,TRUE,FALSE,CURRENT_TIMESTAMP)");
                statement.execute("ALTER TABLE parser_field_reviews ADD CONSTRAINT fk_parser_field_review_example "
                        + "FOREIGN KEY (example_id) REFERENCES parser_training_examples(id) NOT VALID");

                Flyway v46 = flyway(url, username, password, schema).target("46").load();
                assertThrows(FlywayException.class, v46::migrate,
                        "an equivalent-looking but NOT VALID historical FK must not be accepted silently");
                assertEquals(1, count(connection, "SELECT count(*) FROM parser_field_reviews WHERE id=77 "
                        + "AND example_id='" + exampleId + "' AND reviewed_value='1200'"),
                        "rejecting incompatible metadata must preserve historical rows");
            } finally {
                statement.execute("DROP SCHEMA IF EXISTS " + schema + " CASCADE");
            }
        }
    }

    private static FluentConfiguration flyway(String url, String username, String password, String schema) {
        return Flyway.configure().dataSource(url, username, password).schemas(schema).defaultSchema(schema)
                .locations("classpath:db/migration").baselineOnMigrate(true).baselineVersion("1");
    }

    private static int count(Connection connection, String sql) throws Exception {
        try (Statement statement = connection.createStatement(); ResultSet rows = statement.executeQuery(sql)) {
            assertTrue(rows.next());
            return rows.getInt(1);
        }
    }

    private static String text(Connection connection, String sql) throws Exception {
        try (Statement statement = connection.createStatement(); ResultSet rows = statement.executeQuery(sql)) {
            assertTrue(rows.next());
            return rows.getString(1);
        }
    }
}
