package com.indore.pathome.spaces.entity;

import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.FlywayException;
import org.flywaydb.core.api.configuration.FluentConfiguration;
import org.hibernate.StaleObjectStateException;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.boot.MetadataSources;
import org.hibernate.boot.registry.StandardServiceRegistry;
import org.hibernate.boot.registry.StandardServiceRegistryBuilder;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.datasource.init.ScriptUtils;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

/** Verifies the supported pre-Flyway version-1 legacy baseline through the current migration chain. */
@EnabledIfEnvironmentVariable(named = "PATHOME_PACKAGE5_FLYWAY_TEST", matches = "true")
class PathomeSupportedFlywayBaselinePostgresTest {
    private static final String LATEST_VERSION = "48";

    @Test
    void supportedLegacyBaselineUpgradesThroughLatestMigrationWithoutInventingOldOutcomes() throws Exception {
        String url = System.getenv().getOrDefault("SPRING_DATASOURCE_URL", "jdbc:postgresql://localhost:5432/pathome_db");
        String username = System.getenv().getOrDefault("SPRING_DATASOURCE_USERNAME", "pathome");
        String password = System.getenv().getOrDefault("SPRING_DATASOURCE_PASSWORD", "");
        String schema = "pathome_package5_flyway_" + UUID.randomUUID().toString().replace("-", "");

        try (Connection connection = DriverManager.getConnection(url, username, password);
             Statement statement = connection.createStatement()) {
            statement.execute("CREATE SCHEMA " + schema);
            try {
                connection.setSchema(schema);
                ScriptUtils.executeSqlScript(connection,
                        new ClassPathResource("db/baseline/pathome-v1-legacy-core.sql"));
                assertEquals(0, count(connection, "SELECT count(*) FROM information_schema.columns "
                        + "WHERE table_schema=current_schema() AND table_name='rental_details' "
                        + "AND column_name='preferred_tenant'"),
                        "preferred_tenant was introduced by V10 and must not exist in the V1 baseline");
                statement.execute("INSERT INTO users(email,full_name,role,free_visits_remaining) "
                        + "VALUES ('package5-legacy-tenant@example.test','Legacy Tenant','ROLE_TENANT',5)");
                statement.execute("INSERT INTO listings(title,address,city,sector,latitude,longitude,listing_type,status,property_type,bhk_count) "
                        + "VALUES ('Legacy listing','Legacy address','Legacy City','Central',22.0,75.0,'RENT','ACTIVE','FLAT','1BHK')");
                statement.execute("INSERT INTO rental_details(id,available_from) "
                        + "SELECT id,CURRENT_DATE FROM listings WHERE title='Legacy listing'");
                statement.execute("INSERT INTO property_media_assets(listing_id,room_tag,media_url) "
                        + "SELECT id,'GENERAL','https://example.test/legacy.jpg' FROM listings WHERE title='Legacy listing'");
                statement.execute("CREATE TABLE tenant_visit_logs ("
                        + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "tenant_id BIGINT NOT NULL REFERENCES users(id),"
                        + "listing_id BIGINT NOT NULL REFERENCES listings(id),"
                        + "visit_sequence_number INTEGER NOT NULL,"
                        + "commitment_deposit_paid BOOLEAN NOT NULL,"
                        + "commitment_deposit_amount NUMERIC(38,2),"
                        + "txn_id VARCHAR(255),otp_code VARCHAR(255),"
                        + "geofence_verified BOOLEAN NOT NULL,verified_at TIMESTAMP,created_at TIMESTAMP NOT NULL)");
                statement.execute("CREATE INDEX idx_visit_tenant_listing ON tenant_visit_logs(tenant_id,listing_id)");
                statement.execute("CREATE INDEX idx_visit_otp ON tenant_visit_logs(otp_code)");
                statement.execute("INSERT INTO tenant_visit_logs(tenant_id,listing_id,visit_sequence_number,"
                        + "commitment_deposit_paid,commitment_deposit_amount,txn_id,otp_code,geofence_verified,"
                        + "verified_at,created_at) SELECT u.id,l.id,1,FALSE,1250.00,'legacy-txn','legacy-otp',"
                        + "FALSE,NULL,CURRENT_TIMESTAMP FROM users u CROSS JOIN listings l "
                        + "WHERE u.email='package5-legacy-tenant@example.test' AND l.title='Legacy listing'");
                statement.execute("INSERT INTO localities(city,sector_name,created_at) "
                        + "VALUES (' Legacy City ','Unmapped Example Quarter',CURRENT_TIMESTAMP)");

                Flyway beforeV10 = flyway(url, username, password, schema).target("9").load();
                var preV10 = beforeV10.migrate();
                assertTrue(preV10.success);
                assertEquals("9", preV10.targetSchemaVersion.toString());
                assertEquals(0, count(connection, "SELECT count(*) FROM information_schema.columns "
                        + "WHERE table_schema=current_schema() AND table_name='rental_details' "
                        + "AND column_name='preferred_tenant'"),
                        "the column must remain absent before V10 runs");

                Flyway throughBaseline32 = flyway(url, username, password, schema).target("32").load();
                var first = throughBaseline32.migrate();
                assertTrue(first.success);
                assertEquals("32", first.targetSchemaVersion.toString());
                assertEquals(1, count(connection, "SELECT count(*) FROM information_schema.columns "
                        + "WHERE table_schema=current_schema() AND table_name='rental_details' "
                        + "AND column_name='preferred_tenant'"),
                        "V10 must add preferred_tenant to the supported legacy baseline");
                assertEquals(1, count(connection, "SELECT count(*) FROM listings WHERE title='Legacy listing' "
                        + "AND rental_mode='LONG_TERM_RENTAL' AND workflow_status='PUBLISHED'"));
                assertEquals(1, count(connection, "SELECT count(*) FROM property_media_assets "
                        + "WHERE upload_request_id IS NULL AND room_tag='GENERAL'"));

                Flyway throughV40 = flyway(url, username, password, schema).target("40").load();
                var second = throughV40.migrate();
                assertTrue(second.success);
                assertEquals("40", second.targetSchemaVersion.toString());
                long tenantId = scalarLong(connection,
                        "SELECT id FROM users WHERE email='package5-legacy-tenant@example.test'");
                statement.execute("INSERT INTO visit_sessions(tenant_id,status,city) VALUES (" + tenantId
                        + ",'COMPLETED','Legacy City')");

                Flyway latest = flyway(url, username, password, schema).load();
                var third = latest.migrate();
                assertTrue(third.success);
                assertEquals(LATEST_VERSION, third.targetSchemaVersion.toString());
                assertDoesNotThrow(latest::validate);
                assertEquals(1, count(connection, "SELECT count(*) FROM visit_session_outcome_reports r "
                        + "JOIN visit_sessions s ON s.id=r.session_id WHERE s.status='COMPLETED' "
                        + "AND r.state='LEGACY_UNRECORDED' AND r.scope_source='LEGACY_COMPLETED'"));
                assertEquals(0, count(connection, "SELECT count(*) FROM visit_session_item_outcomes"));
                assertEquals(1, count(connection, "SELECT count(*) FROM tenant_visit_logs "
                        + "WHERE txn_id='legacy-txn' AND otp_code='legacy-otp' AND commitment_deposit_amount=1250.00"),
                        "V48 must preserve the historical tenant visit log row and values");
                assertEquals(2, count(connection, "SELECT count(*) FROM pg_constraint "
                        + "WHERE conrelid='tenant_visit_logs'::regclass AND contype='f' AND convalidated "
                        + "AND confupdtype='a' AND confdeltype='a' AND confmatchtype='s' "
                        + "AND NOT condeferrable AND NOT condeferred"),
                        "compatible historical visit-log references retain canonical no-action semantics");
                assertEquals(1, count(connection, "SELECT count(*) FROM property_media_assets "
                        + "WHERE media_url='https://example.test/legacy.jpg' AND room_tag='GENERAL' "
                        + "AND latitude IS NULL AND longitude IS NULL"),
                        "V48 adds nullable coordinates without fabricating historical values");
                assertEquals(2, count(connection, "SELECT count(*) FROM information_schema.columns "
                        + "WHERE table_schema=current_schema() AND table_name='property_media_assets' "
                        + "AND column_name IN ('latitude','longitude') AND data_type='double precision' "
                        + "AND is_nullable='YES'"));
                assertEquals(3, count(connection, "SELECT count(*) FROM information_schema.columns "
                        + "WHERE table_schema=current_schema() AND ((table_name='listings' AND column_name='bhk_count') "
                        + "OR (table_name='property_media_assets' AND column_name IN ('media_url','room_tag'))) "
                        + "AND is_nullable='NO'"));
                long legacyVisitLogId = scalarLong(connection,
                        "SELECT id FROM tenant_visit_logs WHERE txn_id='legacy-txn'");
                statement.execute("INSERT INTO tenant_visit_logs(tenant_id,listing_id,visit_sequence_number,"
                        + "commitment_deposit_paid,geofence_verified,created_at) SELECT u.id,l.id,2,FALSE,FALSE,"
                        + "CURRENT_TIMESTAMP FROM users u CROSS JOIN listings l "
                        + "WHERE u.email='package5-legacy-tenant@example.test' AND l.title='Legacy listing'");
                assertTrue(scalarLong(connection, "SELECT max(id) FROM tenant_visit_logs") > legacyVisitLogId,
                        "V48 must leave the historical identity generator ready for the next row");
                assertEquals(47, count(connection, "SELECT count(*) FROM flyway_schema_history "
                        + "WHERE type='SQL' AND success AND version::integer BETWEEN 2 AND 48"));
                assertEquals(1, count(connection, "SELECT count(*) FROM visit_sessions "
                        + "WHERE status='COMPLETED' AND operational_scope_ready=FALSE "
                        + "AND supported_city_id IS NULL AND operating_team_id IS NULL AND coordinator_user_id IS NULL"));
                assertEquals(0, count(connection, "SELECT count(*) FROM property_visit_requests"),
                        "V45 must leave historical request ownership unresolved instead of inferring it");
                assertEquals(2, count(connection, "SELECT count(*) FROM pg_trigger "
                        + "JOIN pg_class relation ON relation.oid=tgrelid "
                        + "JOIN pg_namespace namespace ON namespace.oid=relation.relnamespace "
                        + "WHERE namespace.nspname=current_schema() "
                        + "AND relation.relname IN ('property_visit_requests','visit_sessions') "
                        + "AND tgname IN ('ct_pvr_ownership_mirror','ct_vs_ownership_mirror') "
                        + "AND tgdeferrable=TRUE AND tginitdeferred=TRUE"));
                assertEquals(4, count(connection, "SELECT count(*) FROM pg_indexes WHERE schemaname=current_schema() "
                        + "AND indexname IN ('idx_pvr_city_intake_order','idx_vs_team_unclaimed_order',"
                        + "'idx_vs_coordinator_work_order','idx_vs_team_workload_order')"));
                assertEquals(14, count(connection, "SELECT count(*) FROM information_schema.columns "
                        + "WHERE table_schema=current_schema() AND table_name='parser_field_reviews'"));
                assertEquals(1, count(connection, "SELECT count(*) FROM information_schema.columns "
                        + "WHERE table_schema=current_schema() AND table_name='parser_field_reviews' "
                        + "AND column_name='id' AND data_type='bigint' AND is_identity='YES' "
                        + "AND identity_generation='BY DEFAULT'"));
                assertEquals(1, count(connection, "SELECT count(*) FROM information_schema.columns "
                        + "WHERE table_schema=current_schema() AND table_name='parser_training_examples' "
                        + "AND column_name='id' AND data_type='character varying' AND character_maximum_length=36"));
                assertEquals(3, count(connection, "SELECT count(*) FROM pg_constraint "
                        + "WHERE conrelid='parser_field_reviews'::regclass "
                        + "AND conname IN ('parser_field_reviews_pkey','fk_parser_field_review_example',"
                        + "'uk_parser_field_example_name')"));
                assertEquals(2, count(connection, "SELECT count(*) FROM pg_indexes WHERE schemaname=current_schema() "
                        + "AND indexname IN ('idx_parser_field_example_eligible','idx_parser_field_name_eligible')"));
                assertEquals(0, count(connection, "SELECT count(*) FROM parser_field_reviews"),
                        "V46 creates schema only and must not fabricate parser review data");
                assertEquals(21, count(connection, "SELECT count(*) FROM information_schema.columns "
                        + "WHERE table_schema=current_schema() AND table_name='parser_training_examples'"));
                assertEquals(11, count(connection, "SELECT count(*) FROM information_schema.columns "
                        + "WHERE table_schema=current_schema() AND table_name='parser_model_versions'"));
                assertEquals(1, count(connection, "SELECT count(*) FROM information_schema.columns "
                        + "WHERE table_schema=current_schema() AND table_name='parser_model_versions' "
                        + "AND column_name='id' AND data_type='bigint' AND is_identity='YES' "
                        + "AND identity_generation='BY DEFAULT'"));
                assertEquals(4, count(connection, "SELECT count(*) FROM pg_indexes WHERE schemaname=current_schema() "
                        + "AND indexname IN ('idx_parser_example_status_created','idx_parser_example_partition_status',"
                        + "'idx_parser_example_batch_property','idx_parser_example_hash_status')"));
                assertEquals(1, count(connection, "SELECT count(*) FROM pg_indexes WHERE schemaname=current_schema() "
                        + "AND indexname='idx_parser_model_status_created'"));
                assertEquals(0, count(connection, "SELECT count(*) FROM parser_training_examples"));
                assertEquals(0, count(connection, "SELECT count(*) FROM parser_model_versions"));
                assertEquals(48, count(connection, "SELECT max(version::integer) FROM flyway_schema_history "
                        + "WHERE type='SQL' AND success"));
                assertDeferredOwnershipMirror(connection, statement);
                assertEquals("1", text(connection,
                        "SELECT version FROM flyway_schema_history WHERE type='BASELINE'"));
                assertEquals(1, count(connection, "SELECT count(*) FROM visit_policy WHERE id=1"));
                assertPackage1aMigrationAndJpaBehavior(connection, url, username, password, schema);
            } finally {
                statement.execute("DROP SCHEMA IF EXISTS " + schema + " CASCADE");
            }
        }
    }

    @Test
    void v48RejectsHistoricalTenantVisitLogCascadeWithoutChangingRows() throws Exception {
        String url = System.getenv().getOrDefault("SPRING_DATASOURCE_URL", "jdbc:postgresql://localhost:5432/pathome_db");
        String username = System.getenv().getOrDefault("SPRING_DATASOURCE_USERNAME", "pathome");
        String password = System.getenv().getOrDefault("SPRING_DATASOURCE_PASSWORD", "");
        String schema = "pathome_v48_cascade_" + UUID.randomUUID().toString().replace("-", "");

        try (Connection connection = DriverManager.getConnection(url, username, password);
             Statement statement = connection.createStatement()) {
            statement.execute("CREATE SCHEMA " + schema);
            try {
                connection.setSchema(schema);
                ScriptUtils.executeSqlScript(connection,
                        new ClassPathResource("db/baseline/pathome-v1-legacy-core.sql"));
                statement.execute("INSERT INTO users(email,full_name,role,free_visits_remaining) "
                        + "VALUES ('v48-cascade-tenant@example.test','Cascade Tenant','ROLE_TENANT',5)");
                statement.execute("INSERT INTO listings(title,address,city,sector,latitude,longitude,listing_type,status,property_type,bhk_count) "
                        + "VALUES ('V48 Cascade listing','Legacy address','Legacy City','Central',22.0,75.0,'RENT','ACTIVE','FLAT','1BHK')");
                statement.execute("INSERT INTO rental_details(id,available_from) "
                        + "SELECT id,CURRENT_DATE FROM listings WHERE title='V48 Cascade listing'");
                statement.execute("INSERT INTO property_media_assets(listing_id,room_tag,media_url) "
                        + "SELECT id,'GENERAL','https://example.test/v48-cascade.jpg' "
                        + "FROM listings WHERE title='V48 Cascade listing'");
                statement.execute("CREATE TABLE tenant_visit_logs ("
                        + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "tenant_id BIGINT NOT NULL CONSTRAINT fk_tenant_visit_logs_tenant "
                        + "REFERENCES users(id) ON DELETE CASCADE,"
                        + "listing_id BIGINT NOT NULL CONSTRAINT fk_tenant_visit_logs_listing REFERENCES listings(id),"
                        + "visit_sequence_number INTEGER NOT NULL,commitment_deposit_paid BOOLEAN NOT NULL,"
                        + "commitment_deposit_amount NUMERIC(38,2),txn_id VARCHAR(255),otp_code VARCHAR(255),"
                        + "geofence_verified BOOLEAN NOT NULL,verified_at TIMESTAMP,created_at TIMESTAMP NOT NULL)");
                statement.execute("INSERT INTO tenant_visit_logs(tenant_id,listing_id,visit_sequence_number,"
                        + "commitment_deposit_paid,commitment_deposit_amount,txn_id,otp_code,geofence_verified,"
                        + "verified_at,created_at) SELECT u.id,l.id,1,FALSE,1250.00,'v48-cascade-txn','v48-cascade-otp',"
                        + "FALSE,NULL,CURRENT_TIMESTAMP FROM users u CROSS JOIN listings l "
                        + "WHERE u.email='v48-cascade-tenant@example.test' AND l.title='V48 Cascade listing'");

                assertTrue(flyway(url, username, password, schema).target("47").load().migrate().success);
                Flyway latest = flyway(url, username, password, schema).load();
                assertThrows(FlywayException.class, latest::migrate,
                        "V48 must reject an existing cascade FK rather than treat it as the mapped reference");
                assertEquals(1, count(connection, "SELECT count(*) FROM tenant_visit_logs "
                        + "WHERE txn_id='v48-cascade-txn' AND otp_code='v48-cascade-otp' "
                        + "AND commitment_deposit_amount=1250.00"),
                        "the failed compatibility check must preserve historical log data");
                assertEquals(1, count(connection, "SELECT count(*) FROM pg_constraint "
                        + "WHERE conrelid='tenant_visit_logs'::regclass AND conname='fk_tenant_visit_logs_tenant' "
                        + "AND contype='f' AND convalidated AND confdeltype='c'"),
                        "the incompatible historical FK remains untouched for an explicit repair decision");
            } finally {
                statement.execute("DROP SCHEMA IF EXISTS " + schema + " CASCADE");
            }
        }
    }

    @Test
    void v48KeepsHighIdsAheadOfSafeGeneratorsAndRejectsUnsafeHistoricalGenerators() throws Exception {
        verifyV48IdentityGenerator("START WITH 900003", true);
        verifyV48IdentityGenerator("START WITH 1", true);
        verifyV48IdentityGenerator("SERIAL", true);
        verifyV48IdentityGenerator(
                "INCREMENT BY -1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 900003", false);
        verifyV48IdentityGenerator("START WITH 1 CYCLE", false);
        verifyV48IdentityGenerator("START WITH 1 CACHE 10", false);
        verifyV48IdentityGenerator("OWNED_WITHOUT_DEFAULT", false);
        verifyV48IdentityGenerator("WRONG_SEQUENCE_DEFAULT", false);
    }

    private static void verifyV48IdentityGenerator(String identityOptions, boolean shouldMigrate) throws Exception {
        String url = System.getenv().getOrDefault("SPRING_DATASOURCE_URL", "jdbc:postgresql://localhost:5432/pathome_db");
        String username = System.getenv().getOrDefault("SPRING_DATASOURCE_USERNAME", "pathome");
        String password = System.getenv().getOrDefault("SPRING_DATASOURCE_PASSWORD", "");
        String schema = "pathome_v48_id_generator_" + UUID.randomUUID().toString().replace("-", "");
        String fixture = UUID.randomUUID().toString().substring(0, 8);

        try (Connection connection = DriverManager.getConnection(url, username, password);
             Statement statement = connection.createStatement()) {
            statement.execute("CREATE SCHEMA " + schema);
            try {
                connection.setSchema(schema);
                ScriptUtils.executeSqlScript(connection,
                        new ClassPathResource("db/baseline/pathome-v1-legacy-core.sql"));
                statement.execute("INSERT INTO users(email,full_name,role,free_visits_remaining) VALUES ('v48-id-"
                        + fixture + "@example.test','Generator Tenant','ROLE_TENANT',5)");
                statement.execute("INSERT INTO listings(title,address,city,sector,latitude,longitude,listing_type,status,property_type,bhk_count) "
                        + "VALUES ('V48 generator " + fixture + "','Legacy address','Legacy City','Central',22.0,75.0,"
                        + "'RENT','ACTIVE','FLAT','1BHK')");
                statement.execute("INSERT INTO rental_details(id,available_from) SELECT id,CURRENT_DATE FROM listings "
                        + "WHERE title='V48 generator " + fixture + "'");
                statement.execute("INSERT INTO property_media_assets(listing_id,room_tag,media_url) "
                        + "SELECT id,'GENERAL','https://example.test/v48-generator.jpg' FROM listings "
                        + "WHERE title='V48 generator " + fixture + "'");
                assertTrue(flyway(url, username, password, schema).target("47").load().migrate().success);

                long tenantId = scalarLong(connection, "SELECT id FROM users WHERE email='v48-id-"
                        + fixture + "@example.test'");
                long listingId = scalarLong(connection, "SELECT id FROM listings WHERE title='V48 generator "
                        + fixture + "'");
                String idDefinition = identityOptions.equals("SERIAL")
                        ? "id BIGSERIAL PRIMARY KEY,"
                        : identityOptions.equals("OWNED_WITHOUT_DEFAULT") || identityOptions.equals("WRONG_SEQUENCE_DEFAULT")
                            ? "id BIGINT PRIMARY KEY,"
                            : "id BIGINT GENERATED BY DEFAULT AS IDENTITY (" + identityOptions + ") PRIMARY KEY,";
                statement.execute("CREATE TABLE tenant_visit_logs ("
                        + idDefinition
                        + "tenant_id BIGINT NOT NULL REFERENCES users(id),listing_id BIGINT NOT NULL REFERENCES listings(id),"
                        + "visit_sequence_number INTEGER NOT NULL,commitment_deposit_paid BOOLEAN NOT NULL,"
                        + "commitment_deposit_amount NUMERIC(38,2),txn_id VARCHAR(255),otp_code VARCHAR(255),"
                        + "geofence_verified BOOLEAN NOT NULL,verified_at TIMESTAMP,created_at TIMESTAMP NOT NULL)");
                if (identityOptions.equals("OWNED_WITHOUT_DEFAULT") || identityOptions.equals("WRONG_SEQUENCE_DEFAULT")) {
                    statement.execute("CREATE SEQUENCE tenant_visit_logs_owned_seq START WITH 900003");
                    statement.execute("ALTER SEQUENCE tenant_visit_logs_owned_seq OWNED BY tenant_visit_logs.id");
                    if (identityOptions.equals("WRONG_SEQUENCE_DEFAULT")) {
                        statement.execute("CREATE SEQUENCE tenant_visit_logs_wrong_seq START WITH 900003");
                        statement.execute("ALTER TABLE tenant_visit_logs ALTER COLUMN id SET DEFAULT "
                                + "nextval('tenant_visit_logs_wrong_seq'::regclass)");
                    }
                }
                statement.execute("INSERT INTO tenant_visit_logs(id,tenant_id,listing_id,visit_sequence_number,"
                        + "commitment_deposit_paid,txn_id,otp_code,geofence_verified,created_at) VALUES "
                        + "(900001," + tenantId + "," + listingId + ",1,FALSE,'v48-generator-one','one',FALSE,CURRENT_TIMESTAMP),"
                        + "(900002," + tenantId + "," + listingId + ",2,FALSE,'v48-generator-two','two',FALSE,CURRENT_TIMESTAMP)");
                if (identityOptions.startsWith("INCREMENT BY -1")) {
                    assertEquals(900003L, scalarLong(connection,
                            "SELECT nextval(pg_get_serial_sequence('tenant_visit_logs','id'))"));
                }

                Flyway v48 = flyway(url, username, password, schema).target("48").load();
                if (!shouldMigrate) {
                    RuntimeException failure = assertThrows(RuntimeException.class, v48::migrate,
                            "unsafe historical identity metadata must fail V48");
                    String expectedFailure = identityOptions.equals("OWNED_WITHOUT_DEFAULT")
                            || identityOptions.equals("WRONG_SEQUENCE_DEFAULT")
                            ? "has an incompatible sequence default"
                            : "requires a noncycling ascending generator with cache 1";
                    assertTrue(rootMessage(failure).contains(expectedFailure),
                            "V48 should identify the unsafe generator metadata");
                    assertEquals(2, count(connection,
                            "SELECT count(*) FROM tenant_visit_logs WHERE id IN (900001,900002)"),
                            "a rejected migration must preserve historical visit rows");
                    assertEquals(2, count(connection, "SELECT count(*) FROM pg_constraint WHERE conrelid="
                            + "'tenant_visit_logs'::regclass AND contype='f' AND convalidated "
                            + "AND confupdtype='a' AND confdeltype='a'"),
                            "generator rejection must leave compatible FK actions intact");
                    return;
                }

                assertTrue(v48.migrate().success);
                assertEquals(2, count(connection,
                        "SELECT count(*) FROM tenant_visit_logs WHERE id IN (900001,900002)"),
                        "migration must preserve historical visit IDs");
                long nextId;
                try (ResultSet row = statement.executeQuery("INSERT INTO tenant_visit_logs(tenant_id,listing_id,"
                        + "visit_sequence_number,commitment_deposit_paid,geofence_verified,created_at) VALUES ("
                        + tenantId + "," + listingId + ",3,FALSE,FALSE,CURRENT_TIMESTAMP) RETURNING id")) {
                    assertTrue(row.next());
                    nextId = row.getLong(1);
                }
                assertTrue(nextId > scalarLong(connection,
                        "SELECT max(id) FROM tenant_visit_logs WHERE visit_sequence_number IN (1,2)"),
                        "every accepted generator must produce an ID above all preserved IDs");
            } finally {
                statement.execute("DROP SCHEMA IF EXISTS " + schema + " CASCADE");
            }
        }
    }

    private static String rootMessage(Throwable failure) {
        Throwable current = failure;
        while (current.getCause() != null) current = current.getCause();
        return current.getMessage() == null ? "" : current.getMessage();
    }

    private static void assertDeferredOwnershipMirror(Connection connection, Statement statement) throws Exception {
        statement.execute("INSERT INTO property_visit_requests(tenant_id,listing_id,session_id,status) "
                + "SELECT s.tenant_id,l.id,s.id,'CANCELLED' FROM visit_sessions s CROSS JOIN listings l "
                + "WHERE s.status='COMPLETED' AND l.title='Legacy listing'");
        long cityId = scalarLong(connection, "SELECT id FROM supported_cities ORDER BY id LIMIT 1");
        long tenantId = scalarLong(connection, "SELECT tenant_id FROM visit_sessions WHERE status='COMPLETED' AND city='Legacy City'");
        assertThrows(SQLException.class, () -> statement.execute("UPDATE visit_sessions "
                + "SET operational_scope_ready=TRUE WHERE status='COMPLETED' AND city='Legacy City'"),
                "ready scope requires a canonical City");
        assertThrows(SQLException.class, () -> statement.execute("UPDATE visit_sessions SET coordinator_user_id="
                + tenantId + " WHERE status='COMPLETED' AND city='Legacy City'"),
                "coordinator ownership requires a Team");
        long anotherCityId = scalarLong(connection, "SELECT id FROM supported_cities WHERE id<>" + cityId + " ORDER BY id LIMIT 1");
        statement.execute("INSERT INTO operating_teams(city_id,code,display_name,active,version,created_at,updated_at) "
                + "VALUES (" + anotherCityId + ",'v45-mismatch-team','V45 mismatch team',TRUE,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)");
        long mismatchedTeamId = scalarLong(connection, "SELECT id FROM operating_teams WHERE code='v45-mismatch-team'");
        assertThrows(SQLException.class, () -> statement.execute("UPDATE visit_sessions SET supported_city_id="
                + cityId + ",operating_team_id=" + mismatchedTeamId
                + " WHERE status='COMPLETED' AND city='Legacy City'"),
                "a Team from another City must violate the composite ownership foreign key");
        assertEquals(1, count(connection, "SELECT count(*) FROM property_visit_requests r "
                + "JOIN visit_sessions s ON s.id=r.session_id WHERE r.status='CANCELLED' "
                + "AND r.operational_scope_ready=FALSE AND s.operational_scope_ready=FALSE"));

        connection.setAutoCommit(false);
        try {
            statement.execute("UPDATE visit_sessions SET supported_city_id=" + cityId
                    + " WHERE status='COMPLETED' AND city='Legacy City'");
            assertThrows(SQLException.class, connection::commit,
                    "A committed linked ownership mismatch must fail at the deferred trigger");
        } finally {
            connection.rollback();
            connection.setAutoCommit(true);
        }

        long intermediateCityId = scalarLong(connection, "SELECT id FROM supported_cities WHERE id<>" + cityId
                + " ORDER BY id LIMIT 1");
        long finalCityId = scalarLong(connection, "SELECT id FROM supported_cities WHERE id<>" + cityId
                + " AND id<>" + intermediateCityId + " ORDER BY id LIMIT 1");
        connection.setAutoCommit(false);
        try {
            statement.execute("UPDATE visit_sessions SET supported_city_id=" + cityId
                    + " WHERE status='COMPLETED' AND city='Legacy City'");
            statement.execute("UPDATE visit_sessions SET supported_city_id=" + intermediateCityId
                    + " WHERE status='COMPLETED' AND city='Legacy City'");
            statement.execute("UPDATE visit_sessions SET supported_city_id=" + finalCityId
                    + " WHERE status='COMPLETED' AND city='Legacy City'");
            statement.execute("UPDATE property_visit_requests SET supported_city_id=" + finalCityId
                    + " WHERE status='CANCELLED'");
            connection.commit();
        } finally {
            if (!connection.getAutoCommit()) connection.rollback();
            connection.setAutoCommit(true);
        }
        assertEquals(1, count(connection, "SELECT count(*) FROM property_visit_requests r "
                + "JOIN visit_sessions s ON s.id=r.session_id WHERE r.supported_city_id=s.supported_city_id "
                + "AND r.supported_city_id=" + finalCityId
                + " AND r.operational_scope_ready=s.operational_scope_ready"));

        connection.setAutoCommit(false);
        try {
            statement.execute("UPDATE property_visit_requests SET supported_city_id=" + intermediateCityId
                    + " WHERE status='CANCELLED'");
            assertThrows(SQLException.class, connection::commit,
                    "a final Session City C and Request City B mismatch must fail at commit");
        } finally {
            connection.rollback();
            connection.setAutoCommit(true);
        }
    }

    private static void assertPackage1aMigrationAndJpaBehavior(Connection connection, String url,
                                                                String username, String password,
                                                                String schema) throws Exception {
        assertEquals(3, count(connection, "SELECT count(*) FROM supported_cities"));
        assertEquals(24, count(connection, "SELECT count(*) FROM localities WHERE supported_city_id IS NOT NULL"));
        assertEquals(25, count(connection, "SELECT count(*) FROM localities"));
        assertEquals(1, count(connection, "SELECT count(*) FROM localities WHERE supported_city_id IS NULL"));
        assertEquals(" Legacy City ", text(connection, "SELECT city FROM localities "
                + "WHERE sector_name='Unmapped Example Quarter'"));
        assertEquals(" Legacy City ", text(connection, "SELECT city FROM localities "
                + "WHERE sector_name='Unmapped Example Quarter' AND supported_city_id IS NULL"));
        assertEquals(0, count(connection, "SELECT count(*) FROM localities l "
                + "JOIN supported_cities c ON c.id=l.supported_city_id "
                + "WHERE l.city <> c.display_name"));

        long indoreId = scalarLong(connection, "SELECT id FROM supported_cities WHERE code='indore'");
        long bhopalId = scalarLong(connection, "SELECT id FROM supported_cities WHERE code='bhopal'");
        long puneId = scalarLong(connection, "SELECT id FROM supported_cities WHERE code='pune'");
        assertThrows(SQLException.class, () -> execute(connection,
                "INSERT INTO supported_cities(code,display_name) VALUES ('indore','Duplicate code')"));

        execute(connection, "INSERT INTO supported_cities(code,display_name) "
                + "VALUES ('indore-central','Indore')");
        assertEquals(2, count(connection, "SELECT count(*) FROM supported_cities WHERE display_name='Indore'"));
        execute(connection, "INSERT INTO operating_teams(city_id,code,display_name) VALUES (" + indoreId
                + ",'north','North Team')");
        execute(connection, "INSERT INTO operating_teams(city_id,code,display_name) VALUES (" + bhopalId
                + ",'north','North Team')");
        assertEquals(2, count(connection, "SELECT count(*) FROM operating_teams WHERE code='north'"));
        assertThrows(SQLException.class, () -> execute(connection,
                "INSERT INTO operating_teams(city_id,code,display_name) VALUES (" + indoreId
                        + ",'north','Duplicate North Team')"));
        assertThrows(SQLException.class, () -> execute(connection,
                "INSERT INTO operating_teams(city_id,code,display_name) VALUES (9223372036854775807,'bad','Bad')"));
        assertThrows(SQLException.class, () -> execute(connection,
                "INSERT INTO localities(city,sector_name,supported_city_id) "
                        + "VALUES ('Unknown','Broken FK',9223372036854775807)"));
        execute(connection, "INSERT INTO localities(city,sector_name,supported_city_id) "
                + "VALUES ('Unknown','Unresolved Null FK',NULL)");
        assertEquals(1, count(connection, "SELECT count(*) FROM localities "
                + "WHERE sector_name='Unresolved Null FK' AND supported_city_id IS NULL"));

        verifyOptimisticVersionsAndMappings(url, username, password, schema, indoreId, bhopalId, puneId);
    }

    private static void verifyOptimisticVersionsAndMappings(String url, String username, String password,
                                                             String schema, long indoreId, long bhopalId,
                                                             long puneId) throws Exception {
        String schemaUrl = url + (url.contains("?") ? "&" : "?") + "currentSchema=" + schema;
        StandardServiceRegistry registry = new StandardServiceRegistryBuilder()
                .applySetting("hibernate.connection.driver_class", "org.postgresql.Driver")
                .applySetting("hibernate.connection.url", schemaUrl)
                .applySetting("hibernate.connection.username", username)
                .applySetting("hibernate.connection.password", password)
                .applySetting("hibernate.default_schema", schema)
                .applySetting("hibernate.dialect", "org.hibernate.dialect.PostgreSQLDialect")
                .applySetting("hibernate.physical_naming_strategy",
                        "org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy")
                .applySetting("hibernate.hbm2ddl.auto", "validate")
                .applySetting("hibernate.show_sql", "false")
                .build();
        try (SessionFactory sessions = new MetadataSources(registry)
                .addAnnotatedClass(SupportedCity.class)
                .addAnnotatedClass(OperatingTeam.class)
                .addAnnotatedClass(Locality.class)
                .addAnnotatedClass(User.class)
                .addAnnotatedClass(EmployeeProfile.class)
                .addAnnotatedClass(StaffAccessGrant.class)
                .addAnnotatedClass(OperationalAuditEvent.class)
                .addAnnotatedClass(ParserTrainingExample.class)
                .addAnnotatedClass(ParserFieldReview.class)
                .addAnnotatedClass(ParserModelVersion.class)
                .buildMetadata()
                .buildSessionFactory()) {
            long teamIndoreId = persistTeam(sessions, indoreId, "south", "Indore South");
            persistTeam(sessions, puneId, "north", "Pune North");
            long localityId = persistLocality(sessions, bhopalId);
            try (Session session = sessions.openSession()) {
                Locality linked = session.find(Locality.class, localityId);
                assertEquals("Bhopal", linked.getCity());
                assertEquals(bhopalId, linked.getSupportedCity().getId());
            }
            long initialCityVersion = readCityVersion(sessions, indoreId);
            try (Session session = sessions.openSession()) {
                Transaction tx = session.beginTransaction();
                SupportedCity city = session.find(SupportedCity.class, indoreId);
                city.setActive(false);
                tx.commit();
                assertEquals(initialCityVersion + 1, city.getVersion());
            }
            try (Session session = sessions.openSession()) {
                Transaction tx = session.beginTransaction();
                SupportedCity updated = session.find(SupportedCity.class, indoreId);
                assertFalse(updated.isActive());
                updated.setActive(true);
                tx.commit();
                assertTrue(updated.isActive());
            }
            assertStaleCityUpdateRejected(sessions, indoreId);
            assertStaleTeamUpdateRejected(sessions, teamIndoreId);
            assertEquals(0, readCityVersion(sessions, bhopalId));
            assertCanonicalCityCodeCannotBeChangedThroughEntityApi();
            assertTeamCityAssociationCannotBeChangedThroughEntityApi();
            verifyStaffAccessMappingsAndVersions(sessions,
                    connectionFor(url, username, password, schema), teamIndoreId);
        } finally {
            StandardServiceRegistryBuilder.destroy(registry);
        }
    }

    private static long persistTeam(SessionFactory sessions, long cityId, String code, String displayName) {
        try (Session session = sessions.openSession()) {
            Transaction tx = session.beginTransaction();
            SupportedCity city = session.find(SupportedCity.class, cityId);
            OperatingTeam team = new OperatingTeam(city, code, displayName, true);
            session.persist(team);
            tx.commit();
            return team.getId();
        }
    }

    private static long persistLocality(SessionFactory sessions, long cityId) {
        try (Session session = sessions.openSession()) {
            Transaction tx = session.beginTransaction();
            SupportedCity city = session.find(SupportedCity.class, cityId);
            Locality locality = new Locality("Bhopal", "Package 1A ORM Link", null, null, null);
            locality.setSupportedCity(city);
            session.persist(locality);
            tx.commit();
            return locality.getId();
        }
    }

    private static long readCityVersion(SessionFactory sessions, long cityId) {
        try (Session session = sessions.openSession()) {
            return session.find(SupportedCity.class, cityId).getVersion();
        }
    }

    private static void assertStaleCityUpdateRejected(SessionFactory sessions, long cityId) {
        try (Session first = sessions.openSession(); Session stale = sessions.openSession()) {
            Transaction firstTx = first.beginTransaction();
            Transaction staleTx = stale.beginTransaction();
            SupportedCity current = first.find(SupportedCity.class, cityId);
            SupportedCity outdated = stale.find(SupportedCity.class, cityId);
            long originalVersion = current.getVersion();
            current.setDisplayName("Indore Updated");
            outdated.setDisplayName("Indore Stale");
            firstTx.commit();
            assertEquals(originalVersion + 1, current.getVersion());
            RuntimeException rejected = assertThrows(RuntimeException.class, staleTx::commit);
            assertTrue(hasStaleObjectCause(rejected), "stale City update must fail through optimistic locking");
            if (staleTx.isActive()) staleTx.rollback();
        }
    }

    private static void assertStaleTeamUpdateRejected(SessionFactory sessions, long teamId) {
        try (Session first = sessions.openSession(); Session stale = sessions.openSession()) {
            Transaction firstTx = first.beginTransaction();
            Transaction staleTx = stale.beginTransaction();
            OperatingTeam current = first.find(OperatingTeam.class, teamId);
            OperatingTeam outdated = stale.find(OperatingTeam.class, teamId);
            long originalVersion = current.getVersion();
            current.setDisplayName("Indore North Updated");
            outdated.setDisplayName("Indore North Stale");
            firstTx.commit();
            assertEquals(originalVersion + 1, current.getVersion());
            RuntimeException rejected = assertThrows(RuntimeException.class, staleTx::commit);
            assertTrue(hasStaleObjectCause(rejected), "stale Team update must fail through optimistic locking");
            if (staleTx.isActive()) staleTx.rollback();
        }
    }

    private static boolean hasStaleObjectCause(Throwable error) {
        for (Throwable cause = error; cause != null; cause = cause.getCause()) {
            if (cause instanceof StaleObjectStateException
                    || cause instanceof jakarta.persistence.OptimisticLockException) return true;
        }
        return false;
    }

    private static void assertTeamCityAssociationCannotBeChangedThroughEntityApi() {
        try {
            var cityField = OperatingTeam.class.getDeclaredField("city");
            assertFalse(cityField.getAnnotation(jakarta.persistence.JoinColumn.class).updatable());
            assertThrows(NoSuchMethodException.class,
                    () -> OperatingTeam.class.getMethod("setCity", SupportedCity.class));
        } catch (NoSuchFieldException error) {
            fail(error);
        }
    }

    private static void assertCanonicalCityCodeCannotBeChangedThroughEntityApi() {
        try {
            var codeField = SupportedCity.class.getDeclaredField("code");
            assertFalse(codeField.getAnnotation(jakarta.persistence.Column.class).updatable());
            assertThrows(NoSuchMethodException.class,
                    () -> SupportedCity.class.getMethod("setCode", String.class));
        } catch (NoSuchFieldException error) {
            fail(error);
        }
    }

    private static Connection connectionFor(String url, String username, String password, String schema)
            throws SQLException {
        Connection connection = DriverManager.getConnection(url, username, password);
        connection.setSchema(schema);
        connection.setAutoCommit(true);
        return connection;
    }

    private static void verifyStaffAccessMappingsAndVersions(SessionFactory sessions, Connection connection,
                                                              long teamId) throws Exception {
        try (connection; Statement statement = connection.createStatement()) {
            statement.execute("INSERT INTO users(email, full_name, role, free_visits_remaining) "
                    + "VALUES ('package1b-staff@example.test', NULL, 'ROLE_TENANT', 0)");
            long userId = scalarLong(connection,
                    "SELECT id FROM users WHERE email='package1b-staff@example.test'");
            statement.execute("INSERT INTO employee_profiles(user_id) VALUES (" + userId + ")");
            assertEquals(1, count(connection, "SELECT count(*) FROM employee_profiles WHERE user_id=" + userId
                    + " AND staff_active=FALSE AND version=0 AND role_type IS NULL AND base_salary IS NULL"));

            long versionProfileId = scalarLong(connection,
                    "SELECT id FROM employee_profiles WHERE user_id=" + userId);
            assertEquals(0, readEmployeeVersion(sessions, versionProfileId));
            try (Session session = sessions.openSession()) {
                Transaction tx = session.beginTransaction();
                EmployeeProfile profile = session.find(EmployeeProfile.class, versionProfileId);
                profile.setStaffActive(true);
                profile.setStaffActivatedAt(java.time.Instant.now());
                tx.commit();
                assertEquals(1, profile.getVersion());
            }
            assertStaleEmployeeProfileUpdateRejected(sessions, versionProfileId);

            String grant = "INSERT INTO staff_access_grants(user_id, capability, scope_type, effective_at, "
                    + "grant_reason_code, provisioning_source) VALUES (" + userId
                    + ",'STAFF_ADMIN','GLOBAL','2025-01-01T00:00:00Z','TEST_GRANT','INITIAL_BOOTSTRAP')";
            statement.execute(grant);
            assertThrows(SQLException.class, () -> statement.execute(grant));
            assertThrows(SQLException.class, () -> statement.execute("INSERT INTO staff_access_grants(user_id, "
                    + "capability, scope_type, city_id, effective_at, grant_reason_code, provisioning_source) "
                    + "VALUES (" + userId + ",'OPS_INTAKE','CITY',NULL,CURRENT_TIMESTAMP,'TEST_GRANT','ADMIN_API')"));
            assertThrows(SQLException.class, () -> statement.execute("INSERT INTO staff_access_grants(user_id, "
                    + "capability, scope_type, effective_at, expires_at, grant_reason_code, provisioning_source) "
                    + "VALUES (" + userId + ",'STAFF_ADMIN','GLOBAL',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP + INTERVAL '1 day',"
                    + "'TEST_GRANT','ADMIN_API')"));
            assertThrows(SQLException.class, () -> statement.execute("INSERT INTO staff_access_grants(user_id, "
                    + "capability, scope_type, city_id, team_id, effective_at, grant_reason_code, provisioning_source) "
                    + "VALUES (" + userId + ",'OPS_INTAKE','CITY',1," + teamId + ",CURRENT_TIMESTAMP,'TEST_GRANT','ADMIN_API')"));

            assertThrows(SQLException.class, () -> statement.execute("INSERT INTO operational_audit_events "
                    + "(actor_kind, action_code, target_type, target_id, reason_code) "
                    + "VALUES ('USER','STAFF_ACTIVATED','USER'," + userId + ",'TEST_REASON')"));
            statement.execute("INSERT INTO operational_audit_events "
                    + "(actor_kind, operator_reference, action_code, target_type, target_id, reason_code, details) "
                    + "VALUES ('DEPLOYMENT_OPERATOR','DEPLOYMENT_CHANGE_1','INITIAL_ADMIN_BOOTSTRAPPED',"
                    + "'USER'," + userId + ",'INITIAL_PROVISIONING','{}'::jsonb)");
            assertThrows(SQLException.class, () -> statement.execute("UPDATE operational_audit_events "
                    + "SET reason_code='CHANGED' WHERE operator_reference='DEPLOYMENT_CHANGE_1'"));
            assertThrows(SQLException.class, () -> statement.execute("UPDATE staff_access_grants "
                    + "SET capability='OPS_INTAKE' WHERE user_id=" + userId));
            assertThrows(SQLException.class, () -> statement.execute("DELETE FROM staff_access_grants WHERE user_id=" + userId));
        }
    }

    private static long readEmployeeVersion(SessionFactory sessions, long profileId) {
        try (Session session = sessions.openSession()) {
            return session.find(EmployeeProfile.class, profileId).getVersion();
        }
    }

    private static void assertStaleEmployeeProfileUpdateRejected(SessionFactory sessions, long profileId) {
        try (Session currentSession = sessions.openSession(); Session staleSession = sessions.openSession()) {
            Transaction currentTx = currentSession.beginTransaction();
            Transaction staleTx = staleSession.beginTransaction();
            EmployeeProfile current = currentSession.find(EmployeeProfile.class, profileId);
            EmployeeProfile stale = staleSession.find(EmployeeProfile.class, profileId);
            current.setStaffActive(false);
            current.setStaffDeactivatedAt(java.time.Instant.now());
            stale.setStaffActive(false);
            stale.setStaffDeactivatedAt(java.time.Instant.now());
            currentTx.commit();
            assertEquals(2, current.getVersion());
            RuntimeException rejected = assertThrows(RuntimeException.class, staleTx::commit);
            assertTrue(hasStaleObjectCause(rejected), "stale staff-state update must fail optimistically");
            if (staleTx.isActive()) staleTx.rollback();
        }
    }

    private static void execute(Connection connection, String sql) throws Exception {
        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }

    private static FluentConfiguration flyway(String url, String username, String password, String schema) {
        return Flyway.configure().dataSource(url, username, password).schemas(schema).defaultSchema(schema)
                .locations("classpath:db/migration").baselineOnMigrate(true).baselineVersion("1");
    }

    private static int count(Connection connection, String sql) throws Exception {
        try (Statement statement = connection.createStatement(); ResultSet rows = statement.executeQuery(sql)) {
            assertTrue(rows.next());
            return rows.getInt(1);
        }
    }

    private static long scalarLong(Connection connection, String sql) throws Exception {
        try (Statement statement = connection.createStatement(); ResultSet rows = statement.executeQuery(sql)) {
            assertTrue(rows.next());
            return rows.getLong(1);
        }
    }

    private static String text(Connection connection, String sql) throws Exception {
        try (Statement statement = connection.createStatement(); ResultSet rows = statement.executeQuery(sql)) {
            assertTrue(rows.next());
            return rows.getString(1);
        }
    }
}
