package com.indore.pathome.spaces.entity;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

/** Runs V30 against a disposable PostgreSQL schema when local DB access is explicitly enabled. */
@EnabledIfEnvironmentVariable(named = "PATHOME_OTP_SCHEMA_TEST", matches = "true")
class UserIdentityMigrationPostgresTest {
    @Test
    void migrationKeepsLegacyUsersAndEnforcesVerifiedUniqueMobileIdentity() throws Exception {
        String url = System.getenv().getOrDefault("SPRING_DATASOURCE_URL", "jdbc:postgresql://localhost:5432/pathome_db");
        String username = System.getenv().getOrDefault("SPRING_DATASOURCE_USERNAME", "pathome");
        String password = System.getenv().getOrDefault("SPRING_DATASOURCE_PASSWORD", "");
        String schema = "otp_ready_test_" + UUID.randomUUID().toString().replace("-", "");

        try (Connection connection = DriverManager.getConnection(url, username, password)) {
            try {
                execute(connection, "CREATE SCHEMA " + schema);
                execute(connection, "CREATE TABLE " + schema + ".users ("
                        + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                        + "email VARCHAR(255) NOT NULL UNIQUE, "
                        + "password_hash VARCHAR(255), phone_number VARCHAR(255))");
                execute(connection, "INSERT INTO " + schema + ".users (email, password_hash, phone_number) VALUES "
                        + "('first@example.test', 'hash', '9876543210'), "
                        + "('second@example.test', NULL, '9876543210')");

                var result = Flyway.configure().dataSource(url, username, password)
                        .schemas(schema).defaultSchema(schema)
                        .baselineOnMigrate(true).baselineVersion("29")
                        .locations("classpath:db/migration").load().migrate();
                assertTrue(result.success);
                assertEquals("30", result.targetSchemaVersion);

                connection.setSchema(schema);
                assertEquals(2, count(connection, "SELECT count(*) FROM users WHERE "
                        + "mobile_number_normalized IS NULL AND mobile_verified_at IS NULL"));
                assertEquals(2, count(connection, "SELECT count(*) FROM users WHERE phone_number = '9876543210'"));

                // Existing email/password users remain valid; multiple NULL mobiles are allowed.
                execute(connection, "INSERT INTO users (email, password_hash) VALUES ('third@example.test', 'hash')");
                assertEquals(3, count(connection, "SELECT count(*) FROM users WHERE mobile_number_normalized IS NULL"));

                // The schema is ready for future mobile-only accounts without exposing signup now.
                execute(connection, "INSERT INTO users (email, password_hash, mobile_number_normalized, mobile_verified_at) "
                        + "VALUES (NULL, NULL, '+919000000001', CURRENT_TIMESTAMP)");
                execute(connection, "INSERT INTO users (email, password_hash, mobile_number_normalized, mobile_verified_at) "
                        + "VALUES (NULL, NULL, '+919000000002', CURRENT_TIMESTAMP)");
                assertEquals(2, count(connection, "SELECT count(*) FROM users WHERE email IS NULL AND password_hash IS NULL"));

                assertEquals("23505", sqlStateForRejectedInsert(connection,
                        "INSERT INTO users (mobile_number_normalized, mobile_verified_at) "
                                + "VALUES ('+919000000001', CURRENT_TIMESTAMP)"));
                assertEquals("23505", sqlStateForRejectedInsert(connection,
                        "INSERT INTO users (email) VALUES ('first@example.test')"));
                assertEquals("23514", sqlStateForRejectedInsert(connection,
                        "INSERT INTO users (mobile_number_normalized, mobile_verified_at) "
                                + "VALUES ('+91 9000000003', CURRENT_TIMESTAMP)"));
                assertEquals("23514", sqlStateForRejectedInsert(connection,
                        "INSERT INTO users (mobile_number_normalized) VALUES ('+919000000003')"));
                assertEquals("23514", sqlStateForRejectedInsert(connection,
                        "INSERT INTO users (mobile_verified_at) VALUES (CURRENT_TIMESTAMP)"));
            } finally {
                execute(connection, "DROP SCHEMA IF EXISTS " + schema + " CASCADE");
            }
        }
    }

    private static void execute(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }

    private static int count(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement(); ResultSet rows = statement.executeQuery(sql)) {
            assertTrue(rows.next());
            return rows.getInt(1);
        }
    }

    private static String sqlStateForRejectedInsert(Connection connection, String sql) {
        SQLException error = assertThrows(SQLException.class, () -> execute(connection, sql));
        return error.getSQLState();
    }
}
