package com.indore.pathome.spaces.entity;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

/** Runs V33 against a disposable PostgreSQL schema when local DB access is explicitly enabled. */
@EnabledIfEnvironmentVariable(named = "PATHOME_VISIT_SESSION_SCHEMA_TEST", matches = "true")
class VisitSessionMigrationPostgresTest {
    @Test
    void migrationPreservesExistingRequestsAndAddsSessionConstraints() throws Exception {
        String url = System.getenv().getOrDefault("SPRING_DATASOURCE_URL", "jdbc:postgresql://localhost:5432/pathome_db");
        String username = System.getenv().getOrDefault("SPRING_DATASOURCE_USERNAME", "pathome");
        String password = System.getenv().getOrDefault("SPRING_DATASOURCE_PASSWORD", "");
        String schema = "visit_session_test_" + UUID.randomUUID().toString().replace("-", "");

        try (Connection connection = DriverManager.getConnection(url, username, password)) {
            try {
                execute(connection, "CREATE SCHEMA " + schema);
                connection.setSchema(schema);
                execute(connection, "CREATE TABLE " + schema + ".users (id BIGINT PRIMARY KEY)");
                execute(connection, "CREATE TABLE " + schema + ".listings (id BIGINT PRIMARY KEY)");
                execute(connection, "CREATE TABLE " + schema + ".localities (id BIGINT PRIMARY KEY)");
                execute(connection, "CREATE TABLE " + schema + ".property_visit_requests ("
                        + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                        + "tenant_id BIGINT NOT NULL REFERENCES users(id), "
                        + "listing_id BIGINT NOT NULL REFERENCES listings(id), "
                        + "budget_min NUMERIC(14,2), budget_max NUMERIC(14,2), preferred_areas VARCHAR(500), "
                        + "move_in_timing VARCHAR(160), preferred_visit_timing VARCHAR(240), tenant_note VARCHAR(2000), "
                        + "status VARCHAR(40) NOT NULL DEFAULT 'RECEIVED', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "
                        + "CONSTRAINT uk_property_visit_request_tenant_listing UNIQUE (tenant_id, listing_id))");
                execute(connection, "INSERT INTO " + schema + ".users (id) VALUES (1), (2)");
                execute(connection, "INSERT INTO " + schema + ".listings (id) VALUES (101), (102), (103)");
                execute(connection, "INSERT INTO " + schema + ".property_visit_requests (tenant_id, listing_id) VALUES (1, 101)");

                var result = Flyway.configure().dataSource(url, username, password)
                        .schemas(schema).defaultSchema(schema)
                        .baselineOnMigrate(true).baselineVersion("32")
                        .locations("classpath:db/migration").load().migrate();
                assertTrue(result.success);
                assertEquals("33", result.targetSchemaVersion);

                connection.setSchema(schema);
                assertEquals(1, count(connection, "SELECT count(*) FROM property_visit_requests WHERE status = 'RECEIVED' AND session_id IS NULL AND version = 0"));
                assertEquals(1, count(connection, "SELECT count(*) FROM visit_policy WHERE id = 1 AND free_visit_sessions_default = 5 AND max_visit_session_duration_minutes = 60"));

                execute(connection, "INSERT INTO visit_sessions (tenant_id, city) VALUES (1, 'Sample City')");
                execute(connection, "INSERT INTO visit_sessions (tenant_id, city) VALUES (1, 'Sample City')");
                execute(connection, "UPDATE property_visit_requests SET session_id = 1 WHERE id = 1");
                execute(connection, "INSERT INTO visit_session_items (session_id, listing_id, position, source_request_id) VALUES (1, 101, 1, 1)");
                execute(connection, "INSERT INTO visit_session_items (session_id, listing_id, position) VALUES (1, 102, 2)");
                assertEquals("101,102", text(connection,
                        "SELECT string_agg(listing_id::text, ',' ORDER BY position) FROM visit_session_items WHERE session_id = 1"));
                execute(connection, "UPDATE visit_session_items SET removed_at = CURRENT_TIMESTAMP, removal_reason = 'Unavailable' WHERE listing_id = 102");
                assertEquals(1, count(connection, "SELECT count(*) FROM visit_session_items WHERE listing_id = 102 AND removed_at IS NOT NULL"));
                assertEquals("23505", sqlStateForRejectedInsert(connection,
                        "INSERT INTO visit_session_items (session_id, listing_id, position) VALUES (1, 101, 3)"));
                assertEquals("23505", sqlStateForRejectedInsert(connection,
                        "INSERT INTO visit_session_items (session_id, listing_id, position) VALUES (1, 103, 2)"));
                assertEquals("23503", sqlStateForRejectedInsert(connection,
                        "INSERT INTO visit_session_items (session_id, listing_id, position, source_request_id) VALUES (1, 103, 3, 1)"));
                assertEquals("23503", sqlStateForRejectedInsert(connection,
                        "INSERT INTO visit_session_items (session_id, listing_id, position, source_request_id) VALUES (2, 101, 1, 1)"));
                assertEquals("23503", sqlStateForRejectedInsert(connection,
                        "INSERT INTO visit_sessions (tenant_id, city) VALUES (999, 'Other City')"));

                execute(connection, "INSERT INTO property_visit_requests (tenant_id, listing_id) VALUES (2, 102)");
                assertEquals("23503", sqlStateForRejectedInsert(connection,
                        "UPDATE property_visit_requests SET session_id = 1 WHERE tenant_id = 2 AND listing_id = 102"));
            } finally {
                execute(connection, "DROP SCHEMA IF EXISTS " + schema + " CASCADE");
            }
        }
    }

    private static void execute(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }

    private static int count(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement(); ResultSet rows = statement.executeQuery(sql)) {
            assertTrue(rows.next());
            return rows.getInt(1);
        }
    }

    private static String text(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement(); ResultSet rows = statement.executeQuery(sql)) {
            assertTrue(rows.next());
            return rows.getString(1);
        }
    }

    private static String sqlStateForRejectedInsert(Connection connection, String sql) {
        SQLException error = assertThrows(SQLException.class, () -> execute(connection, sql));
        return error.getSQLState();
    }
}
